<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Chapter 2: Introduction to Linear Models | Statistics for Data Science - Stat 255: Lawrence University</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The HTML output format for this example is bookdown::gitbook, set in the _output.yml file." />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Chapter 2: Introduction to Linear Models | Statistics for Data Science - Stat 255: Lawrence University" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The HTML output format for this example is bookdown::gitbook, set in the _output.yml file." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Chapter 2: Introduction to Linear Models | Statistics for Data Science - Stat 255: Lawrence University" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The HTML output format for this example is bookdown::gitbook, set in the _output.yml file." />
  

<meta name="author" content="Andrew Sage" />


<meta name="date" content="2021-09-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="cross.html"/>
<script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> url: your book url like <a href="https://bookdown.org/yihui/bookdown" class="uri">https://bookdown.org/yihui/bookdown</a></a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#section-1.1-exploratory-data-analysis"><i class="fa fa-check"></i><b>1.1</b> Section 1.1: Exploratory Data Analysis</a><ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#exploring-movie-data"><i class="fa fa-check"></i><b>1.1.1</b> Exploring Movie Data</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#visualizing-data-1"><i class="fa fa-check"></i><b>1.1.2</b> Visualizing Data 1</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#visualizing-data-2"><i class="fa fa-check"></i><b>1.1.3</b> Visualizing Data 2</a></li>
<li class="chapter" data-level="1.1.4" data-path="index.html"><a href="index.html#visualizing-data-3"><i class="fa fa-check"></i><b>1.1.4</b> Visualizing Data 3</a></li>
<li class="chapter" data-level="1.1.5" data-path="index.html"><a href="index.html#importing-and-exploring-data"><i class="fa fa-check"></i><b>1.1.5</b> Importing and Exploring Data</a></li>
<li class="chapter" data-level="1.1.6" data-path="index.html"><a href="index.html#previewing-the-data---glimpse"><i class="fa fa-check"></i><b>1.1.6</b> Previewing the Data - <code>glimpse()</code></a></li>
<li class="chapter" data-level="1.1.7" data-path="index.html"><a href="index.html#factor-and-numeric-variables"><i class="fa fa-check"></i><b>1.1.7</b> Factor and Numeric Variables</a></li>
<li class="chapter" data-level="1.1.8" data-path="index.html"><a href="index.html#filtering-and-selecting"><i class="fa fa-check"></i><b>1.1.8</b> Filtering and Selecting</a></li>
<li class="chapter" data-level="1.1.9" data-path="index.html"><a href="index.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>1.1.9</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="1.1.10" data-path="index.html"><a href="index.html#previewing-the-data---head"><i class="fa fa-check"></i><b>1.1.10</b> Previewing the Data - <code>head()</code></a></li>
<li class="chapter" data-level="1.1.11" data-path="index.html"><a href="index.html#previewing-the-data-summary"><i class="fa fa-check"></i><b>1.1.11</b> Previewing the Data (<code>summary</code>)</a></li>
<li class="chapter" data-level="1.1.12" data-path="index.html"><a href="index.html#histogram-of-audience-scores"><i class="fa fa-check"></i><b>1.1.12</b> Histogram of Audience Scores</a></li>
<li class="chapter" data-level="1.1.13" data-path="index.html"><a href="index.html#density-plots-of-audience-scores"><i class="fa fa-check"></i><b>1.1.13</b> Density Plots of Audience Scores</a></li>
<li class="chapter" data-level="1.1.14" data-path="index.html"><a href="index.html#boxplot"><i class="fa fa-check"></i><b>1.1.14</b> Boxplot</a></li>
<li class="chapter" data-level="1.1.15" data-path="index.html"><a href="index.html#boxplot-with-datapoints"><i class="fa fa-check"></i><b>1.1.15</b> Boxplot with Datapoints</a></li>
<li class="chapter" data-level="1.1.16" data-path="index.html"><a href="index.html#violin-plot"><i class="fa fa-check"></i><b>1.1.16</b> Violin Plot</a></li>
<li class="chapter" data-level="1.1.17" data-path="index.html"><a href="index.html#scatterplot"><i class="fa fa-check"></i><b>1.1.17</b> Scatterplot</a></li>
<li class="chapter" data-level="1.1.18" data-path="index.html"><a href="index.html#scatterplot-cont."><i class="fa fa-check"></i><b>1.1.18</b> Scatterplot (cont.)</a></li>
<li class="chapter" data-level="1.1.19" data-path="index.html"><a href="index.html#creating-new-variable"><i class="fa fa-check"></i><b>1.1.19</b> Creating New Variable</a></li>
<li class="chapter" data-level="1.1.20" data-path="index.html"><a href="index.html#profitability-by-genre"><i class="fa fa-check"></i><b>1.1.20</b> Profitability by Genre</a></li>
<li class="chapter" data-level="1.1.21" data-path="index.html"><a href="index.html#correlation-plots"><i class="fa fa-check"></i><b>1.1.21</b> Correlation Plots</a></li>
<li class="chapter" data-level="1.1.22" data-path="index.html"><a href="index.html#tabular-summary"><i class="fa fa-check"></i><b>1.1.22</b> Tabular Summary</a></li>
<li class="chapter" data-level="1.1.23" data-path="index.html"><a href="index.html#kable"><i class="fa fa-check"></i><b>1.1.23</b> <code>kable()</code></a></li>
<li class="chapter" data-level="1.1.24" data-path="index.html"><a href="index.html#converting-between-numeric-and-factor"><i class="fa fa-check"></i><b>1.1.24</b> Converting between Numeric and Factor</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#section-1.2-tidy-data"><i class="fa fa-check"></i><b>1.2</b> Section 1.2: Tidy Data</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#representations-of-data"><i class="fa fa-check"></i><b>1.2.1</b> Representations of Data</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#representation-1"><i class="fa fa-check"></i><b>1.2.2</b> Representation 1</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#representation-2"><i class="fa fa-check"></i><b>1.2.3</b> Representation 2</a></li>
<li class="chapter" data-level="1.2.4" data-path="index.html"><a href="index.html#representation-3"><i class="fa fa-check"></i><b>1.2.4</b> Representation 3</a></li>
<li class="chapter" data-level="1.2.5" data-path="index.html"><a href="index.html#representation-4"><i class="fa fa-check"></i><b>1.2.5</b> Representation 4</a></li>
<li class="chapter" data-level="1.2.6" data-path="index.html"><a href="index.html#variables-and-observations"><i class="fa fa-check"></i><b>1.2.6</b> Variables and Observations</a></li>
<li class="chapter" data-level="1.2.7" data-path="index.html"><a href="index.html#tidy-data"><i class="fa fa-check"></i><b>1.2.7</b> Tidy Data</a></li>
<li class="chapter" data-level="1.2.8" data-path="index.html"><a href="index.html#representation-1-tidy"><i class="fa fa-check"></i><b>1.2.8</b> Representation 1 Tidy</a></li>
<li class="chapter" data-level="1.2.9" data-path="index.html"><a href="index.html#representation-2-not-tidy"><i class="fa fa-check"></i><b>1.2.9</b> Representation 2 not Tidy</a></li>
<li class="chapter" data-level="1.2.10" data-path="index.html"><a href="index.html#representation-3-not-tidy"><i class="fa fa-check"></i><b>1.2.10</b> Representation 3 not Tidy</a></li>
<li class="chapter" data-level="1.2.11" data-path="index.html"><a href="index.html#representation-4-is-not-tidy"><i class="fa fa-check"></i><b>1.2.11</b> Representation 4 is not Tidy</a></li>
<li class="chapter" data-level="1.2.12" data-path="index.html"><a href="index.html#why-use-tidy-data"><i class="fa fa-check"></i><b>1.2.12</b> Why Use Tidy Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html"><i class="fa fa-check"></i><b>2</b> Chapter 2: Introduction to Linear Models</a><ul>
<li class="chapter" data-level="2.1" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#section-2.1-models-with-a-categorical-explanatory-variable"><i class="fa fa-check"></i><b>2.1</b> Section 2.1: Models with a Categorical Explanatory Variable</a><ul>
<li class="chapter" data-level="2.1.1" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#models-with-a-categorical-explanatory-variable"><i class="fa fa-check"></i><b>2.1.1</b> Models with a Categorical Explanatory Variable</a></li>
<li class="chapter" data-level="2.1.2" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#variation-in-ames-ia-house-prices"><i class="fa fa-check"></i><b>2.1.2</b> Variation in Ames IA, House Prices</a></li>
<li class="chapter" data-level="2.1.3" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#predicting-price-of-new-house"><i class="fa fa-check"></i><b>2.1.3</b> Predicting Price of New House</a></li>
<li class="chapter" data-level="2.1.4" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#a-very-simple-model"><i class="fa fa-check"></i><b>2.1.4</b> A Very Simple Model</a></li>
<li class="chapter" data-level="2.1.5" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#simple-model-in-r"><i class="fa fa-check"></i><b>2.1.5</b> Simple Model in R</a></li>
<li class="chapter" data-level="2.1.6" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#quantifying-total-variability-in-prices"><i class="fa fa-check"></i><b>2.1.6</b> Quantifying Total Variability in Prices</a></li>
<li class="chapter" data-level="2.1.7" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#total-sum-of-squares"><i class="fa fa-check"></i><b>2.1.7</b> Total Sum of Squares</a></li>
<li class="chapter" data-level="2.1.8" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#total-variation-calculations-in-simple-model"><i class="fa fa-check"></i><b>2.1.8</b> Total Variation Calculations in Simple Model</a></li>
<li class="chapter" data-level="2.1.9" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#adding-information-about-neighborhood"><i class="fa fa-check"></i><b>2.1.9</b> Adding Information about Neighborhood</a></li>
<li class="chapter" data-level="2.1.10" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#explanatory-and-response-variables"><i class="fa fa-check"></i><b>2.1.10</b> Explanatory and Response Variables</a></li>
<li class="chapter" data-level="2.1.11" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#model-by-neighborhood"><i class="fa fa-check"></i><b>2.1.11</b> Model by Neighborhood</a></li>
<li class="chapter" data-level="2.1.12" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#r-output-for-model-with-categorical-variables"><i class="fa fa-check"></i><b>2.1.12</b> R Output for Model with Categorical Variables</a></li>
<li class="chapter" data-level="2.1.13" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#model-notation-for-houses-by-neighborhood"><i class="fa fa-check"></i><b>2.1.13</b> Model Notation for Houses by Neighborhood</a></li>
<li class="chapter" data-level="2.1.14" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#residuals-for-neighborhood-model"><i class="fa fa-check"></i><b>2.1.14</b> Residuals for Neighborhood Model</a></li>
<li class="chapter" data-level="2.1.15" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#residuals-for-neighborhood-model-cont."><i class="fa fa-check"></i><b>2.1.15</b> Residuals for Neighborhood Model (cont.)</a></li>
<li class="chapter" data-level="2.1.16" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#variability-explained-by-model-with-neighborhood"><i class="fa fa-check"></i><b>2.1.16</b> Variability Explained by Model with Neighborhood</a></li>
<li class="chapter" data-level="2.1.17" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#quantifying-variability-explained"><i class="fa fa-check"></i><b>2.1.17</b> Quantifying Variability Explained</a></li>
<li class="chapter" data-level="2.1.18" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#coefficient-of-determination"><i class="fa fa-check"></i><b>2.1.18</b> Coefficient of Determination</a></li>
<li class="chapter" data-level="2.1.19" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#r2-visually"><i class="fa fa-check"></i><b>2.1.19</b> <span class="math inline">\(R^2\)</span> Visually</a></li>
<li class="chapter" data-level="2.1.20" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#variation-explained-by-neighborhood-model"><i class="fa fa-check"></i><b>2.1.20</b> Variation Explained by Neighborhood Model</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#section-2.2-models-with-a-quantitative-explanatory-variable"><i class="fa fa-check"></i><b>2.2</b> Section 2.2: Models with a Quantitative Explanatory Variable</a><ul>
<li class="chapter" data-level="2.2.1" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#model-using-squarefeet-in-house"><i class="fa fa-check"></i><b>2.2.1</b> Model using SquareFeet in House</a></li>
<li class="chapter" data-level="2.2.2" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#model-on-squarefeet-in-house"><i class="fa fa-check"></i><b>2.2.2</b> Model on SquareFeet in House</a></li>
<li class="chapter" data-level="2.2.3" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#model-using-square-feet"><i class="fa fa-check"></i><b>2.2.3</b> Model using Square Feet</a></li>
<li class="chapter" data-level="2.2.4" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#model-for-squarefeet-and-interpretations"><i class="fa fa-check"></i><b>2.2.4</b> Model for SquareFeet and Interpretations</a></li>
<li class="chapter" data-level="2.2.5" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#calculating-predicted-prices"><i class="fa fa-check"></i><b>2.2.5</b> Calculating Predicted Prices</a></li>
<li class="chapter" data-level="2.2.6" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#residuals-for-squarefeet-model"><i class="fa fa-check"></i><b>2.2.6</b> Residuals for SquareFeet Model</a></li>
<li class="chapter" data-level="2.2.7" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#residuals-for-squarefeet-model-cont."><i class="fa fa-check"></i><b>2.2.7</b> Residuals for SquareFeet Model (cont.)</a></li>
<li class="chapter" data-level="2.2.8" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#variation-explained-by-squarefeet-model"><i class="fa fa-check"></i><b>2.2.8</b> Variation Explained by SquareFeet Model</a></li>
<li class="chapter" data-level="2.2.9" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#variation-explained-by-squarefeet-model-1"><i class="fa fa-check"></i><b>2.2.9</b> Variation Explained by SquareFeet Model</a></li>
<li class="chapter" data-level="2.2.10" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#linear-correlation-coefficient"><i class="fa fa-check"></i><b>2.2.10</b> Linear Correlation Coefficient</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#section-2.3-multiple-regression-model"><i class="fa fa-check"></i><b>2.3</b> Section 2.3: Multiple Regression Model</a><ul>
<li class="chapter" data-level="2.3.1" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#multiple-regression-model"><i class="fa fa-check"></i><b>2.3.1</b> Multiple Regression Model</a></li>
<li class="chapter" data-level="2.3.2" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#variable-model-with-constant-slope"><i class="fa fa-check"></i><b>2.3.2</b> 2-Variable Model with Constant Slope</a></li>
<li class="chapter" data-level="2.3.3" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#house-price-2-variable-model-summary"><i class="fa fa-check"></i><b>2.3.3</b> House Price 2-Variable Model Summary</a></li>
<li class="chapter" data-level="2.3.4" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#mr-model-for-squarefeet-and-neighborhood"><i class="fa fa-check"></i><b>2.3.4</b> MR Model for SquareFeet and Neighborhood</a></li>
<li class="chapter" data-level="2.3.5" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#predicting-price-in-mr-model"><i class="fa fa-check"></i><b>2.3.5</b> Predicting Price in MR Model</a></li>
<li class="chapter" data-level="2.3.6" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#risk-of-extrapolation"><i class="fa fa-check"></i><b>2.3.6</b> Risk of Extrapolation</a></li>
<li class="chapter" data-level="2.3.7" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#residuals-for-2-variable-model"><i class="fa fa-check"></i><b>2.3.7</b> Residuals for 2-Variable Model</a></li>
<li class="chapter" data-level="2.3.8" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#residuals-for-2-variable-model-cont."><i class="fa fa-check"></i><b>2.3.8</b> Residuals for 2-Variable Model (cont.)</a></li>
<li class="chapter" data-level="2.3.9" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#variation-explained-by-2-variable-model"><i class="fa fa-check"></i><b>2.3.9</b> Variation Explained by 2-Variable Model</a></li>
<li class="chapter" data-level="2.3.10" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#model-comparison-summary"><i class="fa fa-check"></i><b>2.3.10</b> Model Comparison Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#section-2.4-least-squares-estimation"><i class="fa fa-check"></i><b>2.4</b> Section 2.4: Least-Squares Estimation</a><ul>
<li class="chapter" data-level="2.4.1" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#estimation-of-model-coefficients"><i class="fa fa-check"></i><b>2.4.1</b> Estimation of Model Coefficients</a></li>
<li class="chapter" data-level="2.4.2" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#least-squares-estimation"><i class="fa fa-check"></i><b>2.4.2</b> Least-Squares Estimation</a></li>
<li class="chapter" data-level="2.4.3" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#least-squares-in-general-form"><i class="fa fa-check"></i><b>2.4.3</b> Least Squares in General Form</a></li>
<li class="chapter" data-level="2.4.4" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#least-squares-estimation-in-simple-linear-regression"><i class="fa fa-check"></i><b>2.4.4</b> Least-Squares Estimation in Simple Linear Regression</a></li>
<li class="chapter" data-level="2.4.5" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#least-squares-estimation-in-simple-linear-regression-cont."><i class="fa fa-check"></i><b>2.4.5</b> Least-Squares Estimation in Simple Linear Regression (cont.)</a></li>
<li class="chapter" data-level="2.4.6" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#ls-estimation-for-one-categorical-variable"><i class="fa fa-check"></i><b>2.4.6</b> LS Estimation for One Categorical Variable</a></li>
<li class="chapter" data-level="2.4.7" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#ls-estimation-more-generally"><i class="fa fa-check"></i><b>2.4.7</b> LS Estimation More Generally</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#section-2.5-analysis-of-variance"><i class="fa fa-check"></i><b>2.5</b> Section 2.5: ANalysis Of VAriance</a><ul>
<li class="chapter" data-level="2.5.1" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#analysis-of-variance"><i class="fa fa-check"></i><b>2.5.1</b> ANalysis Of VAriance</a></li>
<li class="chapter" data-level="2.5.2" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#comparing-submodels"><i class="fa fa-check"></i><b>2.5.2</b> Comparing Submodels</a></li>
<li class="chapter" data-level="2.5.3" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#comparison-of-sub-models"><i class="fa fa-check"></i><b>2.5.3</b> Comparison of Sub-Models</a></li>
<li class="chapter" data-level="2.5.4" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#comments-on-f-statistic"><i class="fa fa-check"></i><b>2.5.4</b> Comments on F-Statistic</a></li>
<li class="chapter" data-level="2.5.5" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#anova-f-statistic"><i class="fa fa-check"></i><b>2.5.5</b> ANOVA F-Statistic</a></li>
<li class="chapter" data-level="2.5.6" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#anova-f-statistic-for-m2-vs-m3-in-r"><i class="fa fa-check"></i><b>2.5.6</b> ANOVA F-Statistic for M2 vs M3 in R</a></li>
<li class="chapter" data-level="2.5.7" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#anova-f-statistic-for-m1-vs-m0"><i class="fa fa-check"></i><b>2.5.7</b> ANOVA F-Statistic for M1 vs M0</a></li>
<li class="chapter" data-level="2.5.8" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#anova-f-statistic-for-m0-vs-m1-in-r"><i class="fa fa-check"></i><b>2.5.8</b> ANOVA F-Statistic for M0 vs M1 in R</a></li>
<li class="chapter" data-level="2.5.9" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#anova-f-statistic-for-categorical-variables"><i class="fa fa-check"></i><b>2.5.9</b> ANOVA F-Statistic for Categorical Variables</a></li>
<li class="chapter" data-level="2.5.10" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#f-statistic-for-categorical-variables-illustration"><i class="fa fa-check"></i><b>2.5.10</b> F-Statistic for Categorical Variables Illustration</a></li>
<li class="chapter" data-level="2.5.11" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#alternative-f-statistic-formula"><i class="fa fa-check"></i><b>2.5.11</b> Alternative F-Statistic Formula</a></li>
<li class="chapter" data-level="2.5.12" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#alternative-f-statistic-formula-cont."><i class="fa fa-check"></i><b>2.5.12</b> Alternative F-Statistic Formula (cont.)</a></li>
<li class="chapter" data-level="2.5.13" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#calculating-f-statistic-for-categorical-variables"><i class="fa fa-check"></i><b>2.5.13</b> Calculating F-Statistic for Categorical Variables</a></li>
<li class="chapter" data-level="2.5.14" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#calculating-f-statistic-for-categorical-variables-1"><i class="fa fa-check"></i><b>2.5.14</b> Calculating F-Statistic for Categorical Variables</a></li>
<li class="chapter" data-level="2.5.15" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#alternative-calculation-in-r"><i class="fa fa-check"></i><b>2.5.15</b> Alternative Calculation in R</a></li>
<li class="chapter" data-level="2.5.16" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#f-statistic-in-r-output"><i class="fa fa-check"></i><b>2.5.16</b> F-Statistic in R Output</a></li>
<li class="chapter" data-level="2.5.17" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#f-statistic-in-r-output-m1"><i class="fa fa-check"></i><b>2.5.17</b> F-Statistic in R Output M1</a></li>
<li class="chapter" data-level="2.5.18" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#f-statistic-in-r-output-m2"><i class="fa fa-check"></i><b>2.5.18</b> F-Statistic in R Output M2</a></li>
<li class="chapter" data-level="2.5.19" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#f-statistic-in-r-output-m3"><i class="fa fa-check"></i><b>2.5.19</b> F-Statistic in R Output M3</a></li>
<li class="chapter" data-level="2.5.20" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#when-to-use-f-statistics-for-model-comparison"><i class="fa fa-check"></i><b>2.5.20</b> When to Use F-Statistics for Model Comparison</a></li>
<li class="chapter" data-level="2.5.21" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#interaction-models-with-categorical-variables"><i class="fa fa-check"></i><b>2.5.21</b> Interaction Models with Categorical Variables</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#section-2.6-interaction-models-with-categorical-variables"><i class="fa fa-check"></i><b>2.6</b> Section 2.6 Interaction Models with Categorical Variables</a><ul>
<li class="chapter" data-level="2.6.1" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bear-data"><i class="fa fa-check"></i><b>2.6.1</b> Bear Data</a></li>
<li class="chapter" data-level="2.6.2" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-data-cleaning"><i class="fa fa-check"></i><b>2.6.2</b> Bears Data Cleaning</a></li>
<li class="chapter" data-level="2.6.3" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#examining-the-subset"><i class="fa fa-check"></i><b>2.6.3</b> Examining the Subset</a></li>
<li class="chapter" data-level="2.6.4" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#examining-the-month-variable"><i class="fa fa-check"></i><b>2.6.4</b> Examining the Month Variable</a></li>
<li class="chapter" data-level="2.6.5" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#season-variable"><i class="fa fa-check"></i><b>2.6.5</b> Season Variable</a></li>
<li class="chapter" data-level="2.6.6" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#visualizing-season-variable"><i class="fa fa-check"></i><b>2.6.6</b> Visualizing Season Variable</a></li>
<li class="chapter" data-level="2.6.7" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-data-summary"><i class="fa fa-check"></i><b>2.6.7</b> Bears Data Summary</a></li>
<li class="chapter" data-level="2.6.8" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#histogram-of-bear-weights"><i class="fa fa-check"></i><b>2.6.8</b> Histogram of Bear Weights</a></li>
<li class="chapter" data-level="2.6.9" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#weight-by-season"><i class="fa fa-check"></i><b>2.6.9</b> Weight by Season</a></li>
<li class="chapter" data-level="2.6.10" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#boxplot-of-weight-and-sex"><i class="fa fa-check"></i><b>2.6.10</b> Boxplot of Weight and Sex</a></li>
<li class="chapter" data-level="2.6.11" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-season-and-sex-model-without-interaction"><i class="fa fa-check"></i><b>2.6.11</b> Bears: Season and Sex Model without Interaction</a></li>
<li class="chapter" data-level="2.6.12" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-season-and-sex-model-output"><i class="fa fa-check"></i><b>2.6.12</b> Bears Season and Sex Model Output</a></li>
<li class="chapter" data-level="2.6.13" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#predictions-using-season-and-sex"><i class="fa fa-check"></i><b>2.6.13</b> Predictions using Season and Sex</a></li>
<li class="chapter" data-level="2.6.14" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#weight-using-season-and-sex-model-interpretations"><i class="fa fa-check"></i><b>2.6.14</b> Weight using Season and Sex Model Interpretations</a></li>
<li class="chapter" data-level="2.6.15" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#season-and-sex-with-interaction"><i class="fa fa-check"></i><b>2.6.15</b> Season and Sex with Interaction</a></li>
<li class="chapter" data-level="2.6.16" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-season-and-sex-interaction-model"><i class="fa fa-check"></i><b>2.6.16</b> Bears Season and Sex Interaction Model</a></li>
<li class="chapter" data-level="2.6.17" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#predictions-for-season-and-sex-interaction-model"><i class="fa fa-check"></i><b>2.6.17</b> Predictions for Season and Sex Interaction Model</a></li>
<li class="chapter" data-level="2.6.18" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#season-and-sex-interaction-model-interpretations"><i class="fa fa-check"></i><b>2.6.18</b> Season and Sex Interaction Model Interpretations</a></li>
<li class="chapter" data-level="2.6.19" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#interpretations-for-season-and-sex-interaction-model"><i class="fa fa-check"></i><b>2.6.19</b> Interpretations for Season and Sex Interaction Model</a></li>
<li class="chapter" data-level="2.6.20" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#predicting-new-observations-in-r"><i class="fa fa-check"></i><b>2.6.20</b> Predicting New Observations in R</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#section-2.7-interaction-models-with-categorical-and-quantitative-variables"><i class="fa fa-check"></i><b>2.7</b> Section 2.7 Interaction Models with Categorical and Quantitative Variables</a><ul>
<li class="chapter" data-level="2.7.1" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#summary-of-bears-dataset"><i class="fa fa-check"></i><b>2.7.1</b> Summary of Bears Dataset</a></li>
<li class="chapter" data-level="2.7.2" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#histogram-of-bear-ages"><i class="fa fa-check"></i><b>2.7.2</b> Histogram of Bear Ages</a></li>
<li class="chapter" data-level="2.7.3" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-with-missing-ages"><i class="fa fa-check"></i><b>2.7.3</b> Bears with Missing Ages</a></li>
<li class="chapter" data-level="2.7.4" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#boxplot-of-weight-and-sex-1"><i class="fa fa-check"></i><b>2.7.4</b> Boxplot of Weight and Sex</a></li>
<li class="chapter" data-level="2.7.5" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#boxplot-of-age-and-sex"><i class="fa fa-check"></i><b>2.7.5</b> Boxplot of Age and Sex</a></li>
<li class="chapter" data-level="2.7.6" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#scatterplot-of-age-and-weight"><i class="fa fa-check"></i><b>2.7.6</b> Scatterplot of Age and Weight</a></li>
<li class="chapter" data-level="2.7.7" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-age-and-sex-model"><i class="fa fa-check"></i><b>2.7.7</b> Bears: Age and Sex Model</a></li>
<li class="chapter" data-level="2.7.8" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#constant-slope-model-for-bears"><i class="fa fa-check"></i><b>2.7.8</b> Constant Slope Model for Bears</a></li>
<li class="chapter" data-level="2.7.9" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-age-and-sex-model-output"><i class="fa fa-check"></i><b>2.7.9</b> Bears Age and Sex Model Output</a></li>
<li class="chapter" data-level="2.7.10" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#predicted-bear-weights-from-age-and-sex-model"><i class="fa fa-check"></i><b>2.7.10</b> Predicted Bear Weights from Age and Sex Model</a></li>
<li class="chapter" data-level="2.7.11" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#age-and-sex-model-for-male-and-female-bears"><i class="fa fa-check"></i><b>2.7.11</b> Age and Sex Model for Male and Female Bears</a></li>
<li class="chapter" data-level="2.7.12" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-predictions-with-predict"><i class="fa fa-check"></i><b>2.7.12</b> Bears Predictions with <code>predict</code></a></li>
<li class="chapter" data-level="2.7.13" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#age-and-sex-model-interpretations"><i class="fa fa-check"></i><b>2.7.13</b> Age and Sex Model Interpretations</a></li>
<li class="chapter" data-level="2.7.14" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-age-and-sex-model-with-interaction"><i class="fa fa-check"></i><b>2.7.14</b> Bears Age and Sex Model with Interaction</a></li>
<li class="chapter" data-level="2.7.15" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-age-and-sex-interaction-model"><i class="fa fa-check"></i><b>2.7.15</b> Bears Age and Sex Interaction Model</a></li>
<li class="chapter" data-level="2.7.16" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#summary-for-age-sex-interaction-model"><i class="fa fa-check"></i><b>2.7.16</b> Summary for Age-Sex Interaction Model</a></li>
<li class="chapter" data-level="2.7.17" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#predictions-from-interaction-model-for-bears"><i class="fa fa-check"></i><b>2.7.17</b> Predictions from Interaction Model for Bears</a></li>
<li class="chapter" data-level="2.7.18" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#interaction-model-for-male-and-female-bears"><i class="fa fa-check"></i><b>2.7.18</b> Interaction Model for Male and Female Bears</a></li>
<li class="chapter" data-level="2.7.19" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-interaction-model-predictions-with-predict"><i class="fa fa-check"></i><b>2.7.19</b> Bears Interaction Model Predictions with <code>predict</code></a></li>
<li class="chapter" data-level="2.7.20" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#interpretations-for-age-and-sex-model-with-interaction"><i class="fa fa-check"></i><b>2.7.20</b> Interpretations for Age and Sex Model with Interaction</a></li>
<li class="chapter" data-level="2.7.21" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-weight-model-considerations"><i class="fa fa-check"></i><b>2.7.21</b> Bears Weight Model Considerations</a></li>
<li class="chapter" data-level="2.7.22" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#bears-weight-model-considerations-continued"><i class="fa fa-check"></i><b>2.7.22</b> Bears Weight Model Considerations (continued)</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#section-2.8-interaction-models-with-quantitative-variables"><i class="fa fa-check"></i><b>2.8</b> Section 2.8 Interaction Models with Quantitative Variables</a><ul>
<li class="chapter" data-level="2.8.1" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#cars-dataset"><i class="fa fa-check"></i><b>2.8.1</b> 2015 Cars Dataset</a></li>
<li class="chapter" data-level="2.8.2" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#car-price-and-acceleration-time"><i class="fa fa-check"></i><b>2.8.2</b> Car Price and Acceleration Time</a></li>
<li class="chapter" data-level="2.8.3" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#length-and-sale-price"><i class="fa fa-check"></i><b>2.8.3</b> Length and Sale Price</a></li>
<li class="chapter" data-level="2.8.4" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#relationship-between-acc060-and-length"><i class="fa fa-check"></i><b>2.8.4</b> Relationship between Acc060 and Length</a></li>
<li class="chapter" data-level="2.8.5" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#modeling-price-using-acc060"><i class="fa fa-check"></i><b>2.8.5</b> Modeling Price using Acc060</a></li>
<li class="chapter" data-level="2.8.6" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#modeling-for-car-price-and-acceleration"><i class="fa fa-check"></i><b>2.8.6</b> Modeling for Car Price and Acceleration</a></li>
<li class="chapter" data-level="2.8.7" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#price-and-a060-regression-line"><i class="fa fa-check"></i><b>2.8.7</b> Price and A060 Regression Line</a></li>
<li class="chapter" data-level="2.8.8" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#acc060-model-interpretations"><i class="fa fa-check"></i><b>2.8.8</b> Acc060 Model Interpretations</a></li>
<li class="chapter" data-level="2.8.9" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#modeling-price-using-acc060-and-length"><i class="fa fa-check"></i><b>2.8.9</b> Modeling Price using Acc060 and Length</a></li>
<li class="chapter" data-level="2.8.10" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#model-using-length-and-acceleration-time"><i class="fa fa-check"></i><b>2.8.10</b> Model Using Length and Acceleration Time</a></li>
<li class="chapter" data-level="2.8.11" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#regression-plane"><i class="fa fa-check"></i><b>2.8.11</b> Regression Plane</a></li>
<li class="chapter" data-level="2.8.12" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#acc060-and-length-model-interpretations"><i class="fa fa-check"></i><b>2.8.12</b> Acc060 and Length Model Interpretations</a></li>
<li class="chapter" data-level="2.8.13" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#modeling-price-using-acc060-and-length-with-interaction"><i class="fa fa-check"></i><b>2.8.13</b> Modeling Price using Acc060 and Length with Interaction</a></li>
<li class="chapter" data-level="2.8.14" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#predictions-using-price-acc060-length-model-with-interaction"><i class="fa fa-check"></i><b>2.8.14</b> Predictions using Price, Acc060, Length Model with Interaction</a></li>
<li class="chapter" data-level="2.8.15" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#interaction-model-for-quantitative-variables"><i class="fa fa-check"></i><b>2.8.15</b> Interaction Model for Quantitative Variables</a></li>
<li class="chapter" data-level="2.8.16" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#cars-interaction-model-interpretations"><i class="fa fa-check"></i><b>2.8.16</b> Cars Interaction Model Interpretations</a></li>
<li class="chapter" data-level="2.8.17" data-path="chapter-2-introduction-to-linear-models.html"><a href="chapter-2-introduction-to-linear-models.html#predicting-car-price-using-predict"><i class="fa fa-check"></i><b>2.8.17</b> Predicting Car Price Using <code>predict</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cross.html"><a href="cross.html"><i class="fa fa-check"></i><b>3</b> Cross-references</a><ul>
<li class="chapter" data-level="3.1" data-path="cross.html"><a href="cross.html#chapters-and-sub-chapters"><i class="fa fa-check"></i><b>3.1</b> Chapters and sub-chapters</a></li>
<li class="chapter" data-level="3.2" data-path="cross.html"><a href="cross.html#captioned-figures-and-tables"><i class="fa fa-check"></i><b>3.2</b> Captioned figures and tables</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="parts.html"><a href="parts.html"><i class="fa fa-check"></i><b>4</b> Parts</a></li>
<li class="chapter" data-level="5" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html"><i class="fa fa-check"></i><b>5</b> Footnotes and citations</a><ul>
<li class="chapter" data-level="5.1" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html#footnotes"><i class="fa fa-check"></i><b>5.1</b> Footnotes</a></li>
<li class="chapter" data-level="5.2" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html#citations"><i class="fa fa-check"></i><b>5.2</b> Citations</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="blocks.html"><a href="blocks.html"><i class="fa fa-check"></i><b>6</b> Blocks</a><ul>
<li class="chapter" data-level="6.1" data-path="blocks.html"><a href="blocks.html#equations"><i class="fa fa-check"></i><b>6.1</b> Equations</a></li>
<li class="chapter" data-level="6.2" data-path="blocks.html"><a href="blocks.html#theorems-and-proofs"><i class="fa fa-check"></i><b>6.2</b> Theorems and proofs</a></li>
<li class="chapter" data-level="6.3" data-path="blocks.html"><a href="blocks.html#callout-blocks"><i class="fa fa-check"></i><b>6.3</b> Callout blocks</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sharing-your-book.html"><a href="sharing-your-book.html"><i class="fa fa-check"></i><b>7</b> Sharing your book</a><ul>
<li class="chapter" data-level="7.1" data-path="sharing-your-book.html"><a href="sharing-your-book.html#publishing"><i class="fa fa-check"></i><b>7.1</b> Publishing</a></li>
<li class="chapter" data-level="7.2" data-path="sharing-your-book.html"><a href="sharing-your-book.html#pages"><i class="fa fa-check"></i><b>7.2</b> 404 pages</a></li>
<li class="chapter" data-level="7.3" data-path="sharing-your-book.html"><a href="sharing-your-book.html#metadata-for-sharing"><i class="fa fa-check"></i><b>7.3</b> Metadata for sharing</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics for Data Science - Stat 255: Lawrence University</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter-2-introduction-to-linear-models" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Chapter 2: Introduction to Linear Models</h1>
<div id="section-2.1-models-with-a-categorical-explanatory-variable" class="section level2">
<h2><span class="header-section-number">2.1</span> Section 2.1: Models with a Categorical Explanatory Variable</h2>
<div id="models-with-a-categorical-explanatory-variable" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Models with a Categorical Explanatory Variable</h3>
<p>Learning outcomes:</p>
<ol style="list-style-type: decimal">
<li>Fit model with categorical variables using R.<br />
</li>
<li>Interpret model coefficients.<br />
</li>
<li>Make predictions.<br />
</li>
<li>Calculate proportion of variation explained by model.</li>
</ol>
<p>We'll work with a set of 10 houses sold in Ames, IA between 2006 and 2010.</p>
</div>
<div id="variation-in-ames-ia-house-prices" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Variation in Ames IA, House Prices</h3>
<p>Shown below are the prices of 10 houses sold in Ames, IA between 2006 and 2010.</p>
<pre><code>##  [1] 123.00 187.00 176.50 113.00 163.99 110.00  84.90 150.00 235.00 137.00</code></pre>
<div style="float: left; width: 30%;">
<p><img src="_main_files/figure-html/unnamed-chunk-3-1.png" width="288" /></p>
</div>
<div style="float: left; width: 60%;">

</div>
</div>
<div id="predicting-price-of-new-house" class="section level3">
<h3><span class="header-section-number">2.1.3</span> Predicting Price of New House</h3>
<p>Shown below are the prices of 10 houses sold in Ames, IA between 2006 and 2010.</p>
<pre><code>##  [1] 123.00 187.00 176.50 113.00 163.99 110.00  84.90 150.00 235.00 137.00</code></pre>
<div style="float: left; width: 30%;">
<p><img src="_main_files/figure-html/unnamed-chunk-6-1.png" width="288" /></p>
</div>
<div style="float: right; width: 50%;">
<ul>
<li><p>Suppose we want to predict the price of a new house, that was sold in this time period. (note that new means a house not among the original 10, rather than a newly-built house.)</p></li>
<li><p>Using the information available the best we can do is to use the sample mean for our prediction.</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(Houses<span class="op">$</span>SalePrice)</code></pre></div>
<pre><code>## [1] 148.039</code></pre>
</div>
</div>
<div id="a-very-simple-model" class="section level3">
<h3><span class="header-section-number">2.1.4</span> A Very Simple Model</h3>
<ul>
<li>If we have the prices of <span class="math inline">\(n\)</span> houses, <span class="math inline">\(y_i, y_2, \ldots, y_n\)</span>, and want to predict the price of a new house, we use the model:</li>
</ul>
<p><span class="math display">\[
\widehat{\text{Price}} = \bar{y},  \text{where } \bar{y}=\frac{\displaystyle\sum_{i=1}^ny_i}{n}\]</span>.</p>
<ul>
<li>The symbol <span class="math inline">\(\widehat{\text{Price}}\)</span>, represents the predicted, or expected, price.</li>
</ul>
</div>
<div id="simple-model-in-r" class="section level3">
<h3><span class="header-section-number">2.1.5</span> Simple Model in R</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M0 &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Houses, SalePrice<span class="op">~</span><span class="dv">1</span>)
<span class="kw">summary</span>(M0)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = SalePrice ~ 1, data = Houses)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -63.139 -32.539  -4.539  25.334  86.961 
## 
## Coefficients:
##             Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)   148.04      13.97    10.6 0.0000022 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 44.17 on 9 degrees of freedom</code></pre>
</div>
<div id="quantifying-total-variability-in-prices" class="section level3">
<h3><span class="header-section-number">2.1.6</span> Quantifying Total Variability in Prices</h3>
<ul>
<li><p>Although the mean price represents our best prediction, we certainly shouldn't expect the price of the new house to exactly match the mean of the original 10. There is considerable variability between house prices.</p></li>
<li><p>We can get a sense of how much variability we should expect in our prediction by looking at how much the values in our dataset differ from the predicted (mean) price.</p></li>
<li><p><span class="math inline">\(\displaystyle\sum_{i=1}^n (y_i - \bar{y})=0\)</span>, so this is not a helpful measure.</p></li>
</ul>
<p><img src="_main_files/figure-html/unnamed-chunk-9-1.png" width="768" /></p>
</div>
<div id="total-sum-of-squares" class="section level3">
<h3><span class="header-section-number">2.1.7</span> Total Sum of Squares</h3>
<p>We'll measure total variability in price, using :</p>
<p><span class="math display">\[
\displaystyle\sum_{i=1}^n (y_i - \bar{y})^2
\]</span></p>
<p>We'll call this the total sum of squares, and abbreviate it SST.</p>
<p><img src="SST.png" width="472" height="65%" /></p>
</div>
<div id="total-variation-calculations-in-simple-model" class="section level3">
<h3><span class="header-section-number">2.1.8</span> Total Variation Calculations in Simple Model</h3>
<ul>
<li>Calculate <span class="math inline">\(\displaystyle\sum_{i=1}^n (y_i - \bar{y})\)</span> in R.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(Houses<span class="op">$</span>SalePrice <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(Houses<span class="op">$</span>SalePrice))</code></pre></div>
<pre><code>## [1] 0.0000000000001421085</code></pre>
<ul>
<li>Calculate <span class="math inline">\(SST = \displaystyle\sum_{i=1}^n (y_i - \bar{y})^2\)</span> in R.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>((Houses<span class="op">$</span>SalePrice <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(Houses<span class="op">$</span>SalePrice))<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 17558.52</code></pre>
</div>
<div id="adding-information-about-neighborhood" class="section level3">
<h3><span class="header-section-number">2.1.9</span> Adding Information about Neighborhood</h3>
<ul>
<li><p>Now, suppose we know the neighborhood of each house. We can use this information to improve our predictions.</p></li>
<li><p>The prediction for a new house is given by the average price in that neighborhood.</p></li>
</ul>
<div style="float: left; width:40%;">
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" width="384" /></p>
</div>
<div style="float: right; width: 40%">



<table>
<thead>
<tr class="header">
<th align="left">Neighborhood</th>
<th align="right">AveragePrice</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">CollgCr</td>
<td align="right">195.3300</td>
</tr>
<tr class="even">
<td align="left">Edwards</td>
<td align="right">102.6333</td>
</tr>
<tr class="odd">
<td align="left">NAmes</td>
<td align="right">146.6250</td>
</tr>
</tbody>
</table>
</div>
<div id="explanatory-and-response-variables" class="section level3">
<h3><span class="header-section-number">2.1.10</span> Explanatory and Response Variables</h3>
<ul>
<li><p>The variable we are trying to predict (price) is called the <strong>response variable</strong> (denoted <span class="math inline">\(Y\)</span>).</p></li>
<li><p>The variable(s) we use to help us make the prediction (neighborhood) is(are) called <strong>explanatory variables</strong> (denoted <span class="math inline">\(X\)</span>). These are also referred to as <strong>predictor variables</strong> or <strong>covariates</strong>.</p></li>
</ul>
</div>
<div id="model-by-neighborhood" class="section level3">
<h3><span class="header-section-number">2.1.11</span> Model by Neighborhood</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M_Nbhd &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Houses, SalePrice <span class="op">~</span><span class="st"> </span>Neighborhood)
<span class="kw">summary</span>(M_Nbhd)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = SalePrice ~ Neighborhood, data = Houses)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -31.340 -15.706  -2.477   9.617  39.670 
## 
## Coefficients:
##                     Estimate Std. Error t value   Pr(&gt;|t|)    
## (Intercept)           195.33      14.89  13.118 0.00000349 ***
## NeighborhoodEdwards   -92.70      21.06  -4.402    0.00315 ** 
## NeighborhoodNAmes     -48.71      19.70  -2.473    0.04267 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 25.79 on 7 degrees of freedom
## Multiple R-squared:  0.7348, Adjusted R-squared:  0.6591 
## F-statistic: 9.699 on 2 and 7 DF,  p-value: 0.009603</code></pre>
</div>
<div id="r-output-for-model-with-categorical-variables" class="section level3">
<h3><span class="header-section-number">2.1.12</span> R Output for Model with Categorical Variables</h3>
<pre><code>##                      Estimate Std. Error   t value       Pr(&gt;|t|)
## (Intercept)         195.33000   14.89037 13.117871 0.000003490079
## NeighborhoodEdwards -92.69667   21.05817 -4.401934 0.003149456985
## NeighborhoodNAmes   -48.70500   19.69811 -2.472572 0.042671888138</code></pre>
<ul>
<li>For categorical explanatory variables, R treats the category that comes first alphabetically (in this case CCreek), as a baseline. The intercept gives the prediction for this category.
<ul>
<li>We would expect a house in College Creek to cost 195.33 thousand dollars.</li>
</ul></li>
<li>Each of the other rows in the coefficients table represent the difference between the expected response (price) for that category (neighborhood), compared to the baseline.
<ul>
<li>We would expect a house in Edwards to cost 92.70 thousand less than a house in College Creek. (hence costing 102.63 thousand)<br />
</li>
<li>We would expect a house in North Ames to cost 48.71 thousand less than a house in College Creek. (hence costing 146.62 thousand)</li>
</ul></li>
</ul>
</div>
<div id="model-notation-for-houses-by-neighborhood" class="section level3">
<h3><span class="header-section-number">2.1.13</span> Model Notation for Houses by Neighborhood</h3>
<p>In the model can be expressed in the form:</p>
<p><span class="math inline">\(\widehat{\text{Price}}= b_0+ b_1 \times\text{I}_{\text{Edwards}} +b_2 \times\text{I}_{\text{NAmes}}\)</span></p>
<p><span class="math inline">\(\widehat{\text{Price}}= 195.33+ -92.7 \times\text{I}_{\text{Edwards}} +-48.71 \times\text{I}_{\text{NAmes}}\)</span>, where</p>
<p> represents an indicator variables, taking on values 0 or 1.<br />
- Example: <span class="math display">\[ \text{I}_{\text{Edwards}} =\begin{cases} 
      1 &amp; \text{if house is in Edwards Neighborhood} \\
      0 &amp; \text{otherwise}
       \end{cases}
      \]</span></p>
<p><strong>Predicted Prices:</strong></p>
<p>College Creek: <span class="math inline">\(\widehat{\text{Price}}= 195.33+ -92.7 \times0 +-48.71 \times0 = 195.33\)</span> thousand.</p>
<p>Edwards: <span class="math inline">\(\widehat{\text{Price}}= 195.33+ -92.7 \times1 +-48.71 \times0 = 102.63\)</span> thousand.</p>
<p>North Ames: <span class="math inline">\(\widehat{\text{Price}}= 195.33+ -92.7 \times0 +-48.71 \times1 = 146.62\)</span> thousand.</p>
</div>
<div id="residuals-for-neighborhood-model" class="section level3">
<h3><span class="header-section-number">2.1.14</span> Residuals for Neighborhood Model</h3>
<ul>
<li>The difference between the true and predicted values (<span class="math inline">\(y_i - \hat{y}_i\)</span>) is called the <span class="math inline">\(ith\)</span> <strong>residual</strong>.</li>
</ul>
<p><img src="Cat_Resid.png" width="75%" /></p>
</div>
<div id="residuals-for-neighborhood-model-cont." class="section level3">
<h3><span class="header-section-number">2.1.15</span> Residuals for Neighborhood Model (cont.)</h3>
<pre><code>##    SalePrice Predicted   Residual ResidualSq
## 1     123.00  146.6250 -23.625000  558.14063
## 2     187.00  195.3300  -8.330000   69.38890
## 3     176.50  146.6250  29.875000  892.51563
## 4     113.00  102.6333  10.366667  107.46778
## 5     163.99  195.3300 -31.340000  982.19560
## 6     110.00  102.6333   7.366667   54.26778
## 7      84.90  102.6333 -17.733333  314.47111
## 8     150.00  146.6250   3.375000   11.39063
## 9     235.00  195.3300  39.670000 1573.70890
## 10    137.00  146.6250  -9.625000   92.64062</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(M_Nbhd<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 4656.188</code></pre>
</div>
<div id="variability-explained-by-model-with-neighborhood" class="section level3">
<h3><span class="header-section-number">2.1.16</span> Variability Explained by Model with Neighborhood</h3>
<div style="float: left; width: 50%;">
<p>Intercept-Only Model:</p>
<p><img src="_main_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(M0<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 17558.52</code></pre>
</div>
<div style="float: left; width: 50%;">

<p>Model Using Neighborhood</p>
<p><img src="Cat_Resid.png" width="487" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(M_Nbhd<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 4656.188</code></pre>
</div>
<div id="quantifying-variability-explained" class="section level3">
<h3><span class="header-section-number">2.1.17</span> Quantifying Variability Explained</h3>
<ul>
<li>the total variability in house prices is the sum of the squared differences between price and average price.</li>
</ul>
<p><span class="math display">\[\text{Total Variability in Price}= \text{SST} =\displaystyle\sum_{i=1}^n(y_i-\bar{y})^2\]</span></p>
<ul>
<li>the variability remaining unexplained even after accounting for neighborhood is given by the sum of squared residuals. We abbreviate this SSR, for sum of squared residuals.</li>
</ul>
<p><span class="math display">\[
\text{SSR} = \text{Variability Remaining}=\displaystyle\sum_{i=1}^n(y_i-\hat{y}_i)^2
\]</span></p>
<ul>
<li>the variability explained by the model, abbreviated SSM, is given by</li>
</ul>
<p><span class="math display">\[ \text{SSM} = \text{SST} - \text{SSR} \]</span></p>
<p>It can be shown that <span class="math inline">\(\text{SSM}=\displaystyle\sum_{i=1}^n(\hat{y}_i-\bar{y})^2\)</span>. These abbreviations here vary across texts. Be careful!</p>
</div>
<div id="coefficient-of-determination" class="section level3">
<h3><span class="header-section-number">2.1.18</span> Coefficient of Determination</h3>
<ul>
<li>The <strong>coefficient of determination (abbreviated <span class="math inline">\(R^2\)</span>)</strong> is defined as</li>
</ul>
<p><span class="math display">\[R^2=\frac{\text{Variability Explained by Model}}{\text{Total Variability}}=\frac{\text{SSM}}{\text{SST}} =\frac{\displaystyle\sum_{i=1}^n(\hat{y}_i-\bar{y})^2}{\displaystyle\sum_{i=1}^n(y_i-\bar{y})^2}\]</span></p>
<ul>
<li><span class="math inline">\(R^2\)</span> can be interpreted as the proportion of total variability in the response variable that is explained by the model using the given explanatory variable(s).</li>
</ul>
</div>
<div id="r2-visually" class="section level3">
<h3><span class="header-section-number">2.1.19</span> <span class="math inline">\(R^2\)</span> Visually</h3>
<p><img src="Rsq2.png" width="100%" /></p>
<ul>
<li><p>Blue Area = Total Variability (SST)</p></li>
<li><p>Red Area = Variability Remaining Unexplained by Model (SSR)</p></li>
<li><p>Blue Area - Red Area = Variability Explained by Model (SSM)</p></li>
<li><p><span class="math inline">\(R^2 = \frac{\text{Area of Blue Squares} - \text{Area of Red Squares}}{\text{Area of Blue Squares}} = \frac{\text{SST}-\text{SSR}}{\text{SST}}= \frac{\text{SSM}}{\text{SST}}\)</span></p></li>
</ul>
</div>
<div id="variation-explained-by-neighborhood-model" class="section level3">
<h3><span class="header-section-number">2.1.20</span> Variation Explained by Neighborhood Model</h3>
<div style="float: left; width: 50%;">
<ul>
<li>Total variability in house prices SST = 17,558.52<br />
</li>
<li>Variability remaining unexplained after model accounting for neighborhood: SSR =4,656.188<br />
</li>
<li>Variability explained by model: SSM=SST-SSR=17,558.52 - 4,656.188 = 12,901.81</li>
</ul>
<p><span class="math display">\[ R^2= \frac{12,901.81}{17,558.52}\approx0.7348 \]</span></p>
<ul>
<li><p>73.5% of the variation in house price is explained by the model using neighborhood as an explanatory variable.</p></li>
<li><p>This matches the value of &quot;Multiple R-squared&quot; in the 2nd last line of the R model summary.</p></li>
</ul>
</div>
<div style="float: right; width: 50%;">


<p><img src="_main_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
</div>
</div>
<div id="section-2.2-models-with-a-quantitative-explanatory-variable" class="section level2">
<h2><span class="header-section-number">2.2</span> Section 2.2: Models with a Quantitative Explanatory Variable</h2>
<div id="model-using-squarefeet-in-house" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Model using SquareFeet in House</h3>
<p>Now, suppose we do not know the neighborhood, but do know the size of the house in square feet.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Houses, <span class="kw">aes</span>(<span class="dt">x=</span>SquareFeet, <span class="dt">y=</span>SalePrice)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() </code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-29-1.png" width="576" /></p>
<p>Suppose we want to predict the price of houses with the following number of square feet:</p>
<ul>
<li>990 square feet<br />
</li>
<li>1235 square feet<br />
</li>
<li>1476 square feet</li>
</ul>
</div>
<div id="model-on-squarefeet-in-house" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Model on SquareFeet in House</h3>
<p>Since square feet is a quantitative variable, we can make predictions by fitting a line to the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Houses, <span class="kw">aes</span>(<span class="dt">x=</span>SquareFeet, <span class="dt">y=</span>SalePrice)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method=</span><span class="st">&quot;lm&quot;</span>, <span class="dt">se=</span><span class="ot">FALSE</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-30-1.png" width="576" /></p>
<ul>
<li>For a house with 990 square feet, predicted price is about $125 thousand.<br />
</li>
<li>For a house with 1235 square feet, predicted price is about $155 thousand.<br />
</li>
<li>For a house with 1476 square feet, predicted price is about $185 thousand.</li>
</ul>
</div>
<div id="model-using-square-feet" class="section level3">
<h3><span class="header-section-number">2.2.3</span> Model using Square Feet</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M_SqFt &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Houses, SalePrice<span class="op">~</span>SquareFeet) 
<span class="kw">summary</span>(M_SqFt)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = SalePrice ~ SquareFeet, data = Houses)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -39.235 -14.309   2.052  10.966  43.971 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  6.82000   36.35455   0.188  0.85586   
## SquareFeet   0.12079    0.03022   3.997  0.00397 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 27.06 on 8 degrees of freedom
## Multiple R-squared:  0.6663, Adjusted R-squared:  0.6246 
## F-statistic: 15.97 on 1 and 8 DF,  p-value: 0.003967</code></pre>
</div>
<div id="model-for-squarefeet-and-interpretations" class="section level3">
<h3><span class="header-section-number">2.2.4</span> Model for SquareFeet and Interpretations</h3>
<p>In the model using both square feet and neighborhood, the regression equation is</p>
<p><span class="math inline">\(\widehat{\text{Price}}= b_0+ b_1 \times\text{SquareFeet}\)</span></p>
<p><span class="math inline">\(\widehat{\text{Price}}= 6.82+ 0.121 \times\text{SquareFeet}\)</span></p>
<ul>
<li><p><span class="math inline">\(\widehat{\text{Price}}\)</span> represents the expected, or predicted, price.</p></li>
<li>The slope, <span class="math inline">\(b_1\)</span> represents the expected change in price (in thousands) per one-unit increase in square feet.
<ul>
<li>The price of a house is expected to increase by 121 dollars for each additional square foot.</li>
</ul></li>
<li>The intercept, <span class="math inline">\(b_0\)</span> represents the expected price of a house with 0 square feet.
<ul>
<li>In this situation, this is not a meaningful interpretation.</li>
</ul></li>
</ul>
</div>
<div id="calculating-predicted-prices" class="section level3 smaller">
<h3><span class="header-section-number">2.2.5</span> Calculating Predicted Prices</h3>
<p><span class="math inline">\(\widehat{\text{Price}}= 6.82+ 0.121 \times\text{SquareFeet}\)</span></p>
<ul>
<li>Predicted price for a house with 990 square feet:</li>
</ul>
<p><span class="math inline">\(\widehat{\text{Price}}= 6.82+ 0.121 \times990 = 126.4\)</span> thousand dollars.</p>
<ul>
<li>Predicted price for a house with 1235 square feet:</li>
</ul>
<p><span class="math inline">\(\widehat{\text{Price}}= 6.82+ 0.121 \times1235 = 156.0\)</span> thousand dollars.</p>
<ul>
<li>Predicted price for a house with with 1476 square feet:</li>
</ul>
<p><span class="math inline">\(\widehat{\text{Price}}= 6.82+ 0.121 \times1476 = 185.1\)</span> thousand dollars.</p>
</div>
<div id="residuals-for-squarefeet-model" class="section level3">
<h3><span class="header-section-number">2.2.6</span> Residuals for SquareFeet Model</h3>
<p>The difference between the actual and predicted price is called the <strong>residual.</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M_SqFt<span class="op">$</span>residuals</code></pre></div>
<pre><code>##           1           2           3           4           5           6 
##  11.8149181  -0.8885824  -1.1211847  25.0071576 -18.7044870 -39.2348498 
##           7           8           9          10 
## -34.2574142   4.9929021  43.9708019   8.4207385</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-34-1.png" width="768" /></p>
</div>
<div id="residuals-for-squarefeet-model-cont." class="section level3">
<h3><span class="header-section-number">2.2.7</span> Residuals for SquareFeet Model (cont.)</h3>
<pre><code>##    SalePrice Predicted    Residual   ResidualSq
## 1     123.00 111.18508  11.8149181  139.5922893
## 2     187.00 187.88858  -0.8885824    0.7895786
## 3     176.50 177.62118  -1.1211847    1.2570550
## 4     113.00  87.99284  25.0071576  625.3579304
## 5     163.99 182.69449 -18.7044870  349.8578356
## 6     110.00 149.23485 -39.2348498 1539.3734427
## 7      84.90 119.15741 -34.2574142 1173.5704309
## 8     150.00 145.00710   4.9929021   24.9290718
## 9     235.00 191.02920  43.9708019 1933.4314183
## 10    137.00 128.57926   8.4207385   70.9088361</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(M_SqFt<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 5859.068</code></pre>
</div>
<div id="variation-explained-by-squarefeet-model" class="section level3">
<h3><span class="header-section-number">2.2.8</span> Variation Explained by SquareFeet Model</h3>
<p><img src="Rsq.png" width="65%" /></p>
<p>Created at <a href="http://www.rossmanchance.com/applets/RegShuffle.htm" class="uri">http://www.rossmanchance.com/applets/RegShuffle.htm</a>.</p>
<ul>
<li><p>Blue Area = Total Variability (SST)</p></li>
<li><p>Red Area = Variability Remaining Unexplained by Model (SSR)</p></li>
<li><p>Blue Area - Red Area = Variability Explained by Model (SSM)</p></li>
<li><p><span class="math inline">\(R^2 = \frac{\text{Area of Blue Squares} - \text{Area of Red Squares}}{\text{Area of Blue Squares}} = \frac{\text{SST}-\text{SSR}}{\text{SST}}= \frac{\text{SSM}}{\text{SST}}\)</span></p></li>
</ul>
</div>
<div id="variation-explained-by-squarefeet-model-1" class="section level3">
<h3><span class="header-section-number">2.2.9</span> Variation Explained by SquareFeet Model</h3>
<div style="float: left; width: 50%;">
<ul>
<li>Total variability in house prices SST = 17,558.52<br />
</li>
<li>Variability remaining unexplained after accounting for square feet is SSR = 5,859.07<br />
</li>
<li>Variation explained by model accounting for square feet is <span class="math display">\[ \text{SSM} = 17,558.52 - 5,859.07 = 11,699.45 \]</span></li>
<li><p>Proportion of variation explained by model accounting for square feet is <span class="math display">\[ R^2=\frac{11,699.45}{17,558.52}\approx0.6663\]</span></p></li>
<li><p>66.6% of the variation in house price is explained by the model using square feet as an explanatory variable.</p></li>
</ul>
</div>
<div style="float: left; width: 50%;">

<p><img src="_main_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
</div>
<div id="linear-correlation-coefficient" class="section level3">
<h3><span class="header-section-number">2.2.10</span> Linear Correlation Coefficient</h3>
<p><img src="_main_files/figure-html/unnamed-chunk-39-1.png" width="576" /></p>
<ul>
<li><p>For linear models with a single quantitative variable, the <strong>linear correlation coefficient</strong> <span class="math inline">\(r=\sqrt{R^2}\)</span>, or <span class="math inline">\(r=-\sqrt{R^2}\)</span> (with sign matching the sign on the slope of the line), provides information about the strength and direction of the linear relationship between the variables.</p></li>
<li><p><span class="math inline">\(-1 \leq r \leq 1\)</span>, and <span class="math inline">\(r\)</span> close to <span class="math inline">\(\pm1\)</span> provides evidence of strong linear relationship, while <span class="math inline">\(r\)</span> close to 0 suggests linear relationship is weak.</p></li>
<li><p><span class="math inline">\(r\)</span> is only relevant for models with a single quantitative explanatory variable and a quantitative response variable, while <span class="math inline">\(R^2\)</span> is relevant for any linear model with a quantitative response variable.</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(Houses<span class="op">$</span>SalePrice,Houses<span class="op">$</span>SquareFeet)</code></pre></div>
<pre><code>## [1] 0.8162794</code></pre>
</div>
</div>
<div id="section-2.3-multiple-regression-model" class="section level2">
<h2><span class="header-section-number">2.3</span> Section 2.3: Multiple Regression Model</h2>
<div id="multiple-regression-model" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Multiple Regression Model</h3>
<p>Suppose we have information on both the neighborhood and square feet in the houses. We can account for both of these together using a <strong>multiple regression model</strong>, i.e. a model with more than one explanatory variable.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Houses</code></pre></div>
<pre><code>## # A tibble: 10 x 3
##    Neighborhood SquareFeet SalePrice
##    &lt;fct&gt;             &lt;int&gt;     &lt;dbl&gt;
##  1 NAmes               864     123  
##  2 CollgCr            1499     187  
##  3 NAmes              1414     176. 
##  4 Edwards             672     113  
##  5 CollgCr            1456     164. 
##  6 Edwards            1179     110  
##  7 Edwards             930      84.9
##  8 NAmes              1144     150  
##  9 CollgCr            1525     235  
## 10 NAmes              1008     137</code></pre>
</div>
<div id="variable-model-with-constant-slope" class="section level3 smaller">
<h3><span class="header-section-number">2.3.2</span> 2-Variable Model with Constant Slope</h3>
<p>We'll assume the rate of increase wrt. square feet (i.e. slope) is the same in each neighborhood, but that some neighborhoods are more expensive than others.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-43-1.png" width="768" /></p>
</div>
<div id="house-price-2-variable-model-summary" class="section level3 smaller">
<h3><span class="header-section-number">2.3.3</span> House Price 2-Variable Model Summary</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M_Nbhd_SqFt &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Houses, SalePrice<span class="op">~</span>SquareFeet<span class="op">+</span>Neighborhood)
<span class="kw">summary</span>(M_Nbhd_SqFt)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = SalePrice ~ SquareFeet + Neighborhood, data = Houses)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -29.125  -9.050  -5.653   9.069  37.791 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)         106.72593   68.92188   1.549    0.172
## SquareFeet            0.05933    0.04517   1.314    0.237
## NeighborhoodEdwards -59.09436   32.49761  -1.818    0.119
## NeighborhoodNAmes   -25.81232   25.59807  -1.008    0.352
## 
## Residual standard error: 24.55 on 6 degrees of freedom
## Multiple R-squared:  0.7941, Adjusted R-squared:  0.6911 
## F-statistic: 7.711 on 3 and 6 DF,  p-value: 0.01757</code></pre>
</div>
<div id="mr-model-for-squarefeet-and-neighborhood" class="section level3">
<h3><span class="header-section-number">2.3.4</span> MR Model for SquareFeet and Neighborhood</h3>
<p>In the model using both square feet and neighborhood, the regression equation is</p>
<p><span class="math inline">\(\widehat{\text{Price}}= b_0+ b_1 \times\text{SquareFeet}+ b_2\times\text{I}_{Edwards} + b_3 \times\text{I}_{NAmes}\)</span></p>
<p><span class="math inline">\(\widehat{\text{Price}}= 106.73+ 0.06 \times\text{SquareFeet}+ -59.09 \times\text{I}_{Edwards} +-25.81 \times\text{I}_{NAmes}\)</span></p>
<ul>
<li>The intercept <span class="math inline">\(b_0\)</span> represents the expected price of a house in College Creek with 0 square feet.
<ul>
<li>the intercept has no meaningful interpretation in this context</li>
</ul></li>
<li><span class="math inline">\(b_1\)</span> represents the expected change in price (in thousands) per one-unit increase in square feet, assuming neighborhood is the same.
<ul>
<li>on average, we expect the price of a house to increase by $0.05933 thousand (i.e. $59.33) for each additional square foot, assuming the houses are in the same neighborhood.<br />
</li>
</ul></li>
<li><span class="math inline">\(b_2\)</span> and <span class="math inline">\(b_3\)</span> represent the expected difference in price between a house in the Edwards (or North Ames) neighborhood, compared to the College Creek neighborhood, assuming square footage is the same.
<ul>
<li>We expect a house in the Edwards neighborhood to cost $59.094 less than a house in the College Creek Neighborhood, assuming the houses are the same size.<br />
</li>
<li>We expect a house in the North Ames Neighborhood to cost $25.812 less than a house in the College Creek Neighborhood, assuming the houses are the same size.</li>
</ul></li>
</ul>
</div>
<div id="predicting-price-in-mr-model" class="section level3 smaller">
<h3><span class="header-section-number">2.3.5</span> Predicting Price in MR Model</h3>
<p><span class="math inline">\(\widehat{\text{Price}}= 106.73+ 0.06 \times\text{SquareFeet}+ -59.09 \times\text{I}_{Edwards} +-25.81 \times\text{I}_{NAmes}\)</span></p>
<ul>
<li>848 square foot house in College Creek</li>
</ul>
<p><span class="math inline">\(\widehat{\text{Price}}= 106.73+ 0.06 \times848+ -59.09 \times0 +-25.81 \times 0 =157.0378\)</span> thousand</p>
<ul>
<li>1200 square foot house in North Ames</li>
</ul>
<p><span class="math inline">\(\widehat{\text{Price}}= 106.73+ 0.06 \times1200+ -59.09 \times0 +-25.81 \times1 = 152.1096\)</span> thousand</p>
<ul>
<li>2314 square foot house in Edwards</li>
</ul>
<p><span class="math inline">\(\widehat{\text{Price}}= 106.73+ 0.06 \times\text{SquareFeet}+ -59.09 \times1 +-25.81 \times 0 =184.9212\)</span> thousand</p>
</div>
<div id="risk-of-extrapolation" class="section level3">
<h3><span class="header-section-number">2.3.6</span> Risk of Extrapolation</h3>
<p>Note that 2314 square feet is well outside the range of our observed data. We should treat this prediction with caution, since we don't know whether the trend we see in our data will continue.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-46-1.png" width="768" /></p>
</div>
<div id="residuals-for-2-variable-model" class="section level3">
<h3><span class="header-section-number">2.3.7</span> Residuals for 2-Variable Model</h3>
<p><img src="_main_files/figure-html/unnamed-chunk-47-1.png" width="768" /></p>
</div>
<div id="residuals-for-2-variable-model-cont." class="section level3">
<h3><span class="header-section-number">2.3.8</span> Residuals for 2-Variable Model (cont.)</h3>
<pre><code>##    SalePrice Predicted   Residual  ResidualSq
## 1     123.00  132.1774  -9.177395   84.224570
## 2     187.00  195.6662  -8.666221   75.103383
## 3     176.50  164.8106  11.689410  136.642314
## 4     113.00   87.5034  25.496603  650.076744
## 5     163.99  193.1149 -29.124898  848.259699
## 6     110.00  117.5853  -7.585270   57.536321
## 7      84.90  102.8113 -17.911333  320.815835
## 8     150.00  148.7907   1.209343    1.462509
## 9     235.00  197.2089  37.791119 1428.168680
## 10    137.00  140.7214  -3.721358   13.848508</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(M_Nbhd_SqFt<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 3616.139</code></pre>
</div>
<div id="variation-explained-by-2-variable-model" class="section level3">
<h3><span class="header-section-number">2.3.9</span> Variation Explained by 2-Variable Model</h3>
<div style="float: left; width: 50%;">
<ul>
<li>Total Variation in house prices: SST=17,558.52<br />
</li>
<li>Variation remaining unexplained after accounting for square feet is SSR=3,616.139<br />
</li>
<li><p>Variation explained by model accounting for square feet is <span class="math display">\[SSM=SST-SSR=17,558.52 - 3,616.139 = 13,942.38\]</span></p></li>
<li><p>Proportion of variation in house prices explained by model is:</p></li>
</ul>
<p><span class="math display">\[ R^2 = \frac{13,942.38}{17,558.52}\approx0.794 \]</span></p>
<ul>
<li>79.4% of the variation in house price is explained by the model using square feet as an explanatory variable.</li>
</ul>
</div>
<div style="float: left; width: 50%;">


<p><img src="_main_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
</div>
<div id="model-comparison-summary" class="section level3">
<h3><span class="header-section-number">2.3.10</span> Model Comparison Summary</h3>
<table>
<thead>
<tr class="header">
<th>Model</th>
<th>Variables</th>
<th>Unexplained Variability</th>
<th>Variability Explained</th>
<th><span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>None</td>
<td>17558.52489</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td>Nbhd</td>
<td>4656.1875667</td>
<td>12902.3373233</td>
<td>0.734819</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Sq. Ft.</td>
<td>5859.0678887</td>
<td>11699.4570013</td>
<td>0.6663121</td>
</tr>
<tr class="even">
<td>3</td>
<td>Nbhd, Sq. Ft.</td>
<td>3616.1385638</td>
<td>13942.3863262</td>
<td>0.7940523</td>
</tr>
</tbody>
</table>
<p><strong>Comments on <span class="math inline">\(R^2\)</span>:</strong></p>
<ul>
<li><span class="math inline">\(R^2\)</span> will never decrease when a new variable is added to a model.<br />
</li>
<li>This does not mean that adding more variables to a model always improves its ability to make predictions on new data.<br />
</li>
<li><span class="math inline">\(R^2\)</span> measures how well a model fits the data on which it was built.<br />
</li>
<li>It is possible for a model with high <span class="math inline">\(R^2\)</span> to &quot;overfit&quot; the data it was built from, and thus perform poorly on new data. We will discuss this idea extensively later in the course.</li>
</ul>
</div>
</div>
<div id="section-2.4-least-squares-estimation" class="section level2">
<h2><span class="header-section-number">2.4</span> Section 2.4: Least-Squares Estimation</h2>
<div id="estimation-of-model-coefficients" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Estimation of Model Coefficients</h3>
<p>Learning Outcome:</p>
<ol style="list-style-type: decimal">
<li>Explain how obtain model coefficients <span class="math inline">\(b_0, b_1, b_p\)</span>.</li>
</ol>
</div>
<div id="least-squares-estimation" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Least-Squares Estimation</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Houses, <span class="kw">aes</span>(<span class="dt">x=</span>SquareFeet, <span class="dt">y=</span>SalePrice)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method=</span><span class="st">&quot;lm&quot;</span>, <span class="dt">se=</span><span class="ot">FALSE</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-52-1.png" width="576" /></p>
<ul>
<li><p>The line <span class="math inline">\(\text{Price} = 6.82 + 0.12 \times \text{Square Feet}\)</span> is considered the &quot;line of best fit&quot; in the sense that it minimizes the sum of the squared residuals.</p></li>
<li><p>This <a href="http://www.rossmanchance.com/applets/RegShuffle.htm">Rossman-Chance applet</a> provides an illustration of the line of best fit.</p></li>
</ul>
</div>
<div id="least-squares-in-general-form" class="section level3">
<h3><span class="header-section-number">2.4.3</span> Least Squares in General Form</h3>
<p>Consider a dataset of <span class="math inline">\(n\)</span> observations and p explanatory variables,</p>
<p><span class="math display">\[
\begin{bmatrix}
x_{11}    &amp; x_{12}    &amp; \cdots &amp; x_{1p}  &amp; y_1\\
x_{21}    &amp; x_{22}    &amp; \cdots &amp; x_{2p} &amp; y_2\\
\vdots    &amp; \vdots    &amp;  &amp; \vdots  &amp; \vdots\\
x_{n1}    &amp; x_{n2}    &amp; \cdots &amp; x_{np} &amp; y_n\\
\end{bmatrix}
\]</span></p>
<p>where <span class="math inline">\(y_i\)</span> represents the response variable for case <span class="math inline">\(i\)</span> and <span class="math inline">\(x_{ip}\)</span> represent the value or category indicatory of explanatory variable <span class="math inline">\(p\)</span> for case <span class="math inline">\(i\)</span>.</p>
<p>The line of best fit: <span class="math inline">\(\hat{y}_i = b_0 + b_1x_{i1} + b_2{x_i2} + \ldots + b_px_{ip}\)</span> is, where <span class="math inline">\(b_0, b_1, \ldots, b_p\)</span> are chosen to minimize:</p>
<p><span class="math display">\[ \displaystyle\sum_{i=1}^n (y_i -\hat{y}_i)^2  = \displaystyle\sum_{i=1}^n (y_i - (b_0 + b_1x_{i1} + b_2{x_i2} + \ldots + b_px_{ip}))^2 \]</span></p>
</div>
<div id="least-squares-estimation-in-simple-linear-regression" class="section level3">
<h3><span class="header-section-number">2.4.4</span> Least-Squares Estimation in Simple Linear Regression</h3>
<ul>
<li><p>Consider a <strong>simple linear regression(SLR)</strong> model, which is one with a singe quantitative explanatory variable.</p></li>
<li><p><span class="math inline">\(\hat{y}_i = b_0+b_1x_i\)</span></p></li>
<li><p>we need to minimize:</p></li>
</ul>
<p><span class="math display">\[
\displaystyle\sum_{i=1}^n(y_i-\hat{y}_i)^2 =\displaystyle\sum_{i=1}^n(y_i-(b_0+b_1x_i))^2
\]</span></p>
</div>
<div id="least-squares-estimation-in-simple-linear-regression-cont." class="section level3">
<h3><span class="header-section-number">2.4.5</span> Least-Squares Estimation in Simple Linear Regression (cont.)</h3>
<p>Using calculus, it can be shown that this quantity is minimized when</p>
<ul>
<li><p><span class="math inline">\(b_1=\frac{\displaystyle\sum_{i=1}^{n}(x_i-\bar{x})(y_i-\bar{y})}{\displaystyle\sum_{i=1}^{n}(x_i-\bar{x})^2}=\frac{\displaystyle\sum_{i=1}^{n} x_i y_i-\frac{\displaystyle\sum_{i=1}^{n} x_i \displaystyle\sum_{i=1}^{n} y_i }{n}}{\left(\displaystyle\sum_{i=1}^{n} x_i^2 -\frac{\left(\displaystyle\sum_{i=1}^{n} x_i\right)^2}{n}\right)}\)</span></p></li>
<li><p><span class="math inline">\(b_0=\bar{y}-b_1\bar{x}\)</span> (where <span class="math inline">\(\bar{y}=\frac{\displaystyle\sum_{i=1}^{n}{y_i}}{n}\)</span>, and <span class="math inline">\(\bar{x}=\frac{\displaystyle\sum_{i=1}^{n}{x_i}}{n}\)</span>).</p></li>
</ul>
</div>
<div id="ls-estimation-for-one-categorical-variable" class="section level3">
<h3><span class="header-section-number">2.4.6</span> LS Estimation for One Categorical Variable</h3>
<ul>
<li><p>Consider a model with a single categorical variable (such as neighborhood), with G+1 categories, numbered <span class="math inline">\(g=0,2, \ldots, G\)</span></p></li>
<li><p>Then <span class="math inline">\(\hat{y}_i = b_0 + b_1x_{i1} + \ldots +b_{G}x_{iG}\)</span>.</p></li>
<li><p>we need to minimize</p></li>
</ul>
<p><span class="math display">\[
\displaystyle\sum_{i=1}^n(y_i-\hat{y}_i)^2 =\displaystyle\sum_{i=1}^n(y_i-(b_0 + b_1x_{i1} + \ldots +b_{G}x_{iG}))^2.   
\]</span></p>
<ul>
<li>It can be shown that this is achieved when<br />
</li>
<li><span class="math inline">\(b_0 = \bar{y_0}\)</span> (i.e. the average response in the &quot;baseline group&quot;), and<br />
</li>
<li><span class="math inline">\(b_j = \bar{y_j} - \bar{y}_0\)</span></li>
</ul>
</div>
<div id="ls-estimation-more-generally" class="section level3">
<h3><span class="header-section-number">2.4.7</span> LS Estimation More Generally</h3>
<ul>
<li>For multiple regression models, the logic is the same. We need to choose <span class="math inline">\(b_0, b_1, \ldots, b_p\)</span> in order to minimize</li>
</ul>
<p><span class="math display">\[ \displaystyle\sum_{i=1}^n (y_i -\hat{y}_i)^2  = \displaystyle\sum_{i=1}^n (y_i -(b_0 + b_1x_{i1} + b_2{x_i2} + \ldots + b_px_{ip}))^2 \]</span></p>
<ul>
<li><p>The mathematics, however are more complicated and require inverting a matrix. This goes beyond the scope of this class, so we will let R do the estimation and use the results.</p></li>
<li><p>More on least squares estimation in multiple regression can be found <a href="http://www.math.chalmers.se/Stat/Grundutb/GU/MSG500/A10/lecture5.pdf">here</a>.</p></li>
</ul>
</div>
</div>
<div id="section-2.5-analysis-of-variance" class="section level2">
<h2><span class="header-section-number">2.5</span> Section 2.5: ANalysis Of VAriance</h2>
<div id="analysis-of-variance" class="section level3">
<h3><span class="header-section-number">2.5.1</span> ANalysis Of VAriance</h3>
<p>Learning Outcomes</p>
<ol style="list-style-type: decimal">
<li>Use ANOVA F-statistics to compare models and sub-models.<br />
</li>
<li>Use F-statistics to measure variability between groups, compared to variability within groups.</li>
</ol>
</div>
<div id="comparing-submodels" class="section level3">
<h3><span class="header-section-number">2.5.2</span> Comparing Submodels</h3>
<table>
<thead>
<tr class="header">
<th>Model</th>
<th>Variables</th>
<th>Unexplained Variability</th>
<th>Variability Explained</th>
<th><span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>None</td>
<td>17558.52489</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td>Nbhd.</td>
<td>4656.1875667</td>
<td>12902.3373233</td>
<td>0.734819</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Sq. Ft</td>
<td>5859.0678887</td>
<td>11699.4570013</td>
<td>0.6663121</td>
</tr>
<tr class="even">
<td>3</td>
<td>Nbhd, Sq. Ft.</td>
<td>3616.1385638</td>
<td>13942.3863262</td>
<td>0.7940523</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Notice that Model 1 is a submodel of Model 3, since all variables used in Model 1 are also used in Model 3.</p></li>
<li><p>Model 2 is also a submodel of Model 3.</p></li>
<li><p>Model 0 is a submodel of Models 1, 2, and 3.</p></li>
<li><p>Models 1 and 2 are not submodels of each other, since Model 1 contains a variable used in Model 2 and Model 2 contains a variable not used in Model 1.</p></li>
</ul>
</div>
<div id="comparison-of-sub-models" class="section level3">
<h3><span class="header-section-number">2.5.3</span> Comparison of Sub-Models</h3>
<p>When one model is a submodel of another, we can compare the amount of variability explained by the models, using a technique known as <strong>ANalysis Of VAriance (ANOVA)</strong>.</p>
<p>Reduced Model: <span class="math inline">\(\hat{y}_i = b_0 + b_1x_{i1} + b_2{x_i2} + \ldots + b_qx_{iq}\)</span></p>
<p>Full Model: <span class="math inline">\(\hat{y}_i = b_0 + b_1x_{i1} + b_2{x_i2} + \ldots + b_qx_{iq} + b_{q+1}x_{i{q+1}} \ldots + b_px_{ip}\)</span></p>
<p>p = ## variables in Full Model<br />
q = ## variables in Reduced Model<br />
n = number of observations</p>
<p>We calculate a statistic called F:</p>
<p><span class="math display">\[
\begin{aligned}
F  &amp;=\frac{\frac{\text{Unexplained Variability in Reduced Model}-\text{Unexplained Variability in Full Model}}{p-q}}{\frac{\text{Unexplained Variability in Full Model}}{n-(p+1)}} \\
&amp;= \frac{\frac{\text{SSR}_{\text{Reduced}}-\text{SSR}_{\text{Full}}}{p-q}}{\frac{\text{SSR}_{\text{Full}}}{n-(p+1)}}
\end{aligned}
\]</span></p>
</div>
<div id="comments-on-f-statistic" class="section level3">
<h3><span class="header-section-number">2.5.4</span> Comments on F-Statistic</h3>
<ul>
<li><p>The F-statistic measures the amount of variability explained by adding additional variable(s) to the model, relative to the total amount of unexplained variability.</p></li>
<li>Large values of F indicate that adding the additional explanatory variables is helpful in explaining variability in the response variable<br />
</li>
<li>Small values of F indicate that adding new explanatory variables variables does not make much of a difference in explaining variability in the response variable<br />
</li>
<li><p>What counts as &quot;large&quot; is depends on <span class="math inline">\(n, p,\)</span> and <span class="math inline">\(q\)</span>. We will revisit this later in the course.</p></li>
</ul>
</div>
<div id="anova-f-statistic" class="section level3">
<h3><span class="header-section-number">2.5.5</span> ANOVA F-Statistic</h3>
<p>Let's Calculate an ANOVA F-Statistic to compare Models 2 and 3.</p>
<p>Reduced Model: <span class="math inline">\(\widehat{\text{Price}}= b_0+ b_1 \times\text{SquareFeet}\)</span></p>
<p>Full Model: <span class="math inline">\(\widehat{\text{Price}}= b_0+ b_1 \times\text{SquareFeet}+ b_2\times\text{I}_{Edwards} + b_3 \times\text{I}_{NAmes}\)</span></p>
<p><span class="math display">\[
\begin{aligned}
F &amp;= \frac{\frac{\text{SSR}_{\text{Reduced}}-\text{SSR}_{\text{Full}}}{p-q}}{\frac{\text{SSR}_{\text{Full}}}{n-(p+1)}} \\
&amp;=\frac{\frac{5,859.07-3,616.14}{3-1}}{\frac{3,616.13}{10-(3+1)}} \\
\end{aligned}
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">SSR2 &lt;-<span class="st"> </span><span class="kw">sum</span>(M_SqFt<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>); SSR3 &lt;-<span class="st"> </span><span class="kw">sum</span>(M_Nbhd_SqFt<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>);
((SSR2<span class="op">-</span>SSR3)<span class="op">/</span>(<span class="dv">3</span><span class="op">-</span><span class="dv">1</span>))<span class="op">/</span>((SSR3)<span class="op">/</span>(<span class="dv">10</span><span class="op">-</span>(<span class="dv">3</span><span class="op">+</span><span class="dv">1</span>)))</code></pre></div>
<pre><code>## [1] 1.860766</code></pre>
</div>
<div id="anova-f-statistic-for-m2-vs-m3-in-r" class="section level3">
<h3><span class="header-section-number">2.5.6</span> ANOVA F-Statistic for M2 vs M3 in R</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(M_SqFt, M_Nbhd_SqFt)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: SalePrice ~ SquareFeet
## Model 2: SalePrice ~ SquareFeet + Neighborhood
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1      8 5859.1                           
## 2      6 3616.1  2    2242.9 1.8608 0.2351</code></pre>
<p>Notice the F-statistic has the same value.</p>
<p>Later, we will examine what this tells us about adding Neighborhood to a model already containing square feet as an explanatory variable.</p>
</div>
<div id="anova-f-statistic-for-m1-vs-m0" class="section level3">
<h3><span class="header-section-number">2.5.7</span> ANOVA F-Statistic for M1 vs M0</h3>
<p>Now, let's compare Models 0 and 1.</p>
<p>Reduced Model: <span class="math inline">\(\widehat{\text{Price}}_i = b_0\)</span></p>
<p>Full Model: <span class="math inline">\(\widehat{\text{Price}}_i = b_0 + b_1\text{I}_{\text{Edwards}} + b_2\text{I}_{\text{NAmes}}\)</span></p>
<p><span class="math display">\[
\begin{aligned}
F &amp;= \frac{\frac{\text{SSR}_{\text{Reduced}}-\text{SSR}_{\text{Full}}}{p-q}}{\frac{\text{SSR}_{\text{Full}}}{n-(p+1)}} \\
&amp;=\frac{\frac{17558.52-4656.19}{2-0}}{\frac{4656.19}{10-(2+1)}}
\end{aligned}
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">SSR0 &lt;-<span class="st"> </span><span class="kw">sum</span>(M0<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>); SSR1 &lt;-<span class="st"> </span><span class="kw">sum</span>(M_Nbhd<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>);
((SSR0<span class="op">-</span>SSR1)<span class="op">/</span>(<span class="dv">2</span><span class="op">-</span><span class="dv">0</span>))<span class="op">/</span>((SSR1)<span class="op">/</span>(<span class="dv">10</span><span class="op">-</span>(<span class="dv">2</span><span class="op">+</span><span class="dv">1</span>)))</code></pre></div>
<pre><code>## [1] 9.698531</code></pre>
</div>
<div id="anova-f-statistic-for-m0-vs-m1-in-r" class="section level3">
<h3><span class="header-section-number">2.5.8</span> ANOVA F-Statistic for M0 vs M1 in R</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(M0, M_Nbhd)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: SalePrice ~ 1
## Model 2: SalePrice ~ Neighborhood
##   Res.Df     RSS Df Sum of Sq      F   Pr(&gt;F)   
## 1      9 17558.5                                
## 2      7  4656.2  2     12902 9.6985 0.009603 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="anova-f-statistic-for-categorical-variables" class="section level3">
<h3><span class="header-section-number">2.5.9</span> ANOVA F-Statistic for Categorical Variables</h3>
<ul>
<li>The difference between M1 and M0 is that M1 considers the house's neighborhood, while M0 does not.<br />
</li>
<li>If neighborhood is helpful in modeling house price, then we would expect to see a high F-statistic.<br />
</li>
<li>Another way to think about this is that if the amount of variability in house prices between different neighborhoods is large, relative to the amount of variability within neighborhoods, then the F-statistic should be large.<br />
</li>
<li>In fact, an alternative (an mathematically equivalent) way to calculate the F-statistic is to calculate the ratio of variability between different neighborhoods, relative to the amount of variability within neighborhoods.</li>
</ul>
</div>
<div id="f-statistic-for-categorical-variables-illustration" class="section level3">
<h3><span class="header-section-number">2.5.10</span> F-Statistic for Categorical Variables Illustration</h3>
<p>An F-statistic compares the amount of variability between groups to the amount of variability within groups.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-58-1.png" width="864" /></p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Scenario 1</th>
<th>Scenario 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>variation between groups</td>
<td>High</td>
<td>Low</td>
</tr>
<tr class="even">
<td>variation within groups</td>
<td>Low</td>
<td>High</td>
</tr>
<tr class="odd">
<td>F Statistic</td>
<td>Large</td>
<td>Small</td>
</tr>
<tr class="even">
<td>Result</td>
<td>Evidence of Group Differences</td>
<td>No evidence of differences</td>
</tr>
</tbody>
</table>
</div>
<div id="alternative-f-statistic-formula" class="section level3">
<h3><span class="header-section-number">2.5.11</span> Alternative F-Statistic Formula</h3>
<p>For a categorical variable with <span class="math inline">\(g\)</span> groups,</p>
<ul>
<li><p>let <span class="math inline">\(\bar{y}_{1\cdot}, \ldots, \bar{y}_{g\cdot}\)</span> represent the mean response for each group.</p></li>
<li><p>let <span class="math inline">\(n_1, \ldots, n_g\)</span> represent the sample size for each group</p></li>
<li><p>Then <span class="math inline">\(\frac{\displaystyle\sum_{i=1}^g\sum_{j=1}^{n_i}n_i(y_{i\cdot}-\bar{y}_{\cdot\cdot})^2}{g-1}\)</span> gives a measure of how much the group means differ, and</p></li>
<li><p><span class="math inline">\(\frac{\displaystyle\sum_{i=1}^g\sum_{j=1}^{n_i}(y_{ij}-\bar{y}_{i\cdot})^2}{n-g}\)</span> gives a measure of how much individual observations differ within groups</p></li>
</ul>
</div>
<div id="alternative-f-statistic-formula-cont." class="section level3">
<h3><span class="header-section-number">2.5.12</span> Alternative F-Statistic Formula (cont.)</h3>
<ul>
<li>An alternative formula for this F-statistic is:</li>
</ul>
<p><span class="math display">\[
F= \frac{\text{Variability between Neighborhoods}}{\text{Variability within Neighborhoods}}= \frac{\frac{\displaystyle\sum_{i=1}^g\sum_{j=1}^{n_i}n_i(y_{i\cdot}-\bar{y}_{\cdot\cdot})^2}{g-1}}{\frac{\displaystyle\sum_{i=1}^g\sum_{j=1}^{n_i}(y_{ij}-\bar{y}_{i\cdot})^2}{n-g}}
\]</span></p>
<ul>
<li>It can be shown that this statistic is equivalent to the one we saw previously.</li>
</ul>
</div>
<div id="calculating-f-statistic-for-categorical-variables" class="section level3">
<h3><span class="header-section-number">2.5.13</span> Calculating F-Statistic for Categorical Variables</h3>
<p>We have seen previously that:</p>
<ul>
<li><span class="math inline">\(\bar{y}_{\cdot\cdot}=148.039\)</span> (overall average price), and <span class="math inline">\(n=10\)</span></li>
<li><span class="math inline">\(\bar{y}_{1\cdot}=195.330\)</span> (average price in College Creek), and <span class="math inline">\(n_1=3\)</span><br />
</li>
<li><span class="math inline">\(\bar{y}_{2\cdot}=102.633\)</span> (average price in Edwards), and <span class="math inline">\(n_2=4\)</span><br />
</li>
<li><span class="math inline">\(\bar{y}_{3\cdot}=146.625\)</span> (average price in North Ames), and <span class="math inline">\(n_3=3\)</span></li>
</ul>
<p>Then,</p>
<ul>
<li><p><span class="math inline">\(\frac{\displaystyle\sum_{i=1}^g\sum_{j=1}^{n_i}(y_{i\cdot}-\bar{y}_{\cdot\cdot})^2}{g-1} = \frac{3(195.330-148.039)^2+3(102.633-148.039)^2+4(146.625-148.039)^2}{3-1} = \frac{12902}{2}\)</span>, and</p></li>
<li><p><span class="math inline">\(\frac{\displaystyle\sum_{i=1}^g\sum_{j=1}^{n_i}(y_{ij}-\bar{y}_{i\cdot})^2}{n-g} = \frac{(123.00-146.625)^2+ (187.00 - 195.33)^2 + \ldots + (137.00-146.625)^2}{10-3} = \frac{4656}{7}\)</span></p></li>
</ul>
</div>
<div id="calculating-f-statistic-for-categorical-variables-1" class="section level3 cont">
<h3><span class="header-section-number">2.5.14</span> Calculating F-Statistic for Categorical Variables</h3>
<p><span class="math display">\[
F= \frac{\frac{\displaystyle\sum_{i=1}^g\sum_{j=1}^{n_i}n_i(y_{i\cdot}-\bar{y}_{\cdot\cdot})^2}{g-1}}{\frac{\displaystyle\sum_{i=1}^g\sum_{j=1}^{n_i}(y_{ij}-\bar{y}_{i\cdot})^2}{n-g}} = \frac{\frac{(195.330-148.039)^2+(102.633-148.039)^2+(146.625-148.039)^2}{3-1}}{\frac{(123.00-146.625)^2+ (187.00 - 195.33)^2 + \ldots + (137.00-146.625)^2}{10-3}} = \frac{\frac{12902}{2}}{\frac{4656}{7}}
\]</span></p>
<ul>
<li>Note that the quantity in the the quantity in the third line is equivalent to the sum of the squared residuals using M2. Thus, we can calculate F using:</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">((<span class="dv">3</span><span class="op">*</span>(<span class="fl">195.330</span><span class="op">-</span><span class="fl">148.039</span>)<span class="op">^</span><span class="dv">2</span><span class="op">+</span><span class="dv">3</span><span class="op">*</span>(<span class="fl">102.633</span><span class="op">-</span><span class="fl">148.039</span>)<span class="op">^</span><span class="dv">2</span><span class="op">+</span><span class="dv">4</span><span class="op">*</span>(<span class="fl">146.625</span><span class="op">-</span><span class="fl">148.039</span>)<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span>(<span class="dv">3</span><span class="op">-</span><span class="dv">1</span>))<span class="op">/</span>(<span class="kw">sum</span>(M_Nbhd<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span>(<span class="dv">10</span><span class="op">-</span><span class="dv">3</span>))</code></pre></div>
<pre><code>## [1] 9.6986</code></pre>
</div>
<div id="alternative-calculation-in-r" class="section level3">
<h3><span class="header-section-number">2.5.15</span> Alternative Calculation in R</h3>
<p>This interpretation of the F-statistic can be seen using the AOV command in R.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AOV_Nbhd &lt;-<span class="st"> </span><span class="kw">aov</span>(<span class="dt">data=</span>Houses, SalePrice<span class="op">~</span>Neighborhood)
<span class="kw">summary</span>(AOV_Nbhd)</code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)   
## Neighborhood  2  12902    6451   9.699 0.0096 **
## Residuals     7   4656     665                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<ul>
<li>The <em>Neighborhood</em> line represents the variability between neighborhoods<br />
</li>
<li><p>The <em>Residuals</em> line represents the variability within neighborhoods</p></li>
<li><p>The first two columns give the quantities we use in our formula. The third column, representing the ratio of the first two columns is called a <strong>mean square.</strong></p></li>
</ul>
</div>
<div id="f-statistic-in-r-output" class="section level3">
<h3><span class="header-section-number">2.5.16</span> F-Statistic in R Output</h3>
<p>The last line in the summary output includes the F-statistic for the specified model, compared to a reduced model that includes only the intercept.</p>
<p>Reduced Model: <span class="math inline">\(\widehat{Y}= b_0\)</span></p>
<p>Full Model: <span class="math inline">\(\widehat{Y}= b_0+ b_1 X_{i1}+ \ldots+ b_p X_{ip}\)</span></p>
<p>This statistic addresses the question <em>&quot;Do any of the explanatory variables help explain variability in Y?&quot;</em>.</p>
<p>When there is only one explanatory variable in the model, this statistic can be used to test whether there is evidence that this statistic is associated with <span class="math inline">\(Y\)</span>.</p>
</div>
<div id="f-statistic-in-r-output-m1" class="section level3">
<h3><span class="header-section-number">2.5.17</span> F-Statistic in R Output M1</h3>
<p>The F-statistic compares a full model that includes neighborhood to a reduced model that predicts each price using the overall average.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(M_Nbhd)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = SalePrice ~ Neighborhood, data = Houses)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -31.340 -15.706  -2.477   9.617  39.670 
## 
## Coefficients:
##                     Estimate Std. Error t value   Pr(&gt;|t|)    
## (Intercept)           195.33      14.89  13.118 0.00000349 ***
## NeighborhoodEdwards   -92.70      21.06  -4.402    0.00315 ** 
## NeighborhoodNAmes     -48.71      19.70  -2.473    0.04267 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 25.79 on 7 degrees of freedom
## Multiple R-squared:  0.7348, Adjusted R-squared:  0.6591 
## F-statistic: 9.699 on 2 and 7 DF,  p-value: 0.009603</code></pre>
</div>
<div id="f-statistic-in-r-output-m2" class="section level3">
<h3><span class="header-section-number">2.5.18</span> F-Statistic in R Output M2</h3>
<p>The F-statistic compares a full model that includes square feet to a reduced model that predicts each price using the overall average.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(M_SqFt)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = SalePrice ~ SquareFeet, data = Houses)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -39.235 -14.309   2.052  10.966  43.971 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  6.82000   36.35455   0.188  0.85586   
## SquareFeet   0.12079    0.03022   3.997  0.00397 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 27.06 on 8 degrees of freedom
## Multiple R-squared:  0.6663, Adjusted R-squared:  0.6246 
## F-statistic: 15.97 on 1 and 8 DF,  p-value: 0.003967</code></pre>
</div>
<div id="f-statistic-in-r-output-m3" class="section level3">
<h3><span class="header-section-number">2.5.19</span> F-Statistic in R Output M3</h3>
<p>The F-statistic compares a full model that includes square feet and neighborhood to a reduced model that predicts each price using only the overall average.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(M_Nbhd_SqFt)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = SalePrice ~ SquareFeet + Neighborhood, data = Houses)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -29.125  -9.050  -5.653   9.069  37.791 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)         106.72593   68.92188   1.549    0.172
## SquareFeet            0.05933    0.04517   1.314    0.237
## NeighborhoodEdwards -59.09436   32.49761  -1.818    0.119
## NeighborhoodNAmes   -25.81232   25.59807  -1.008    0.352
## 
## Residual standard error: 24.55 on 6 degrees of freedom
## Multiple R-squared:  0.7941, Adjusted R-squared:  0.6911 
## F-statistic: 7.711 on 3 and 6 DF,  p-value: 0.01757</code></pre>
</div>
<div id="when-to-use-f-statistics-for-model-comparison" class="section level3">
<h3><span class="header-section-number">2.5.20</span> When to Use F-Statistics for Model Comparison</h3>
<ul>
<li>We have used F-statistics to compare models 1 and 3, and models 0 and 2.</li>
<li>We could also calculate F-statistics comparing models 2 and 3, models 0 and 1, and models 0 and 3.<br />
</li>
<li>We cannot use an F-statistic to compare models 1 and 2, since neither is a submodel of the other.<br />
</li>
<li>When comparing a model to the &quot;intercept-only&quot; model, we can use the model summary output. When comparing other to other submodels, use the <code>aov()</code> or <code>anova()</code> commands.</li>
</ul>
</div>
<div id="interaction-models-with-categorical-variables" class="section level3">
<h3><span class="header-section-number">2.5.21</span> Interaction Models with Categorical Variables</h3>
<p>Learning Outcomes</p>
<ol style="list-style-type: decimal">
<li>Fit models involving interactions.</li>
<li>Make interpret regression coefficients for models with interactions.<br />
</li>
<li>Compare and contrast the assumptions behind models with and without interaction terms.</li>
</ol>
<ul>
<li>We will build a model to predict the weight of a bear, using other characteristics including season, sex, and age.</li>
</ul>
</div>
</div>
<div id="section-2.6-interaction-models-with-categorical-variables" class="section level2">
<h2><span class="header-section-number">2.6</span> Section 2.6 Interaction Models with Categorical Variables</h2>
<div id="bear-data" class="section level3">
<h3><span class="header-section-number">2.6.1</span> Bear Data</h3>
<p>Data are available in the <code>Bolstad</code> R package. We examine the structure of the dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(Bolstad)
<span class="kw">data</span>(bears)
<span class="kw">glimpse</span>(bears)</code></pre></div>
<pre><code>## Rows: 143
## Columns: 12
## $ ID      &lt;int&gt; 39, 41, 41, 41, 41, 43, 43, 45, 45, 48, 69, 83, 83, 83, 83, 91…
## $ Age     &lt;int&gt; 19, 19, 20, 23, 29, 19, 20, 55, 67, 81, NA, 115, 117, 124, 140…
## $ Month   &lt;int&gt; 7, 7, 8, 11, 5, 7, 8, 7, 7, 9, 10, 7, 9, 4, 8, 8, 4, 9, 7, 4, …
## $ Sex     &lt;int&gt; 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1,…
## $ Head.L  &lt;dbl&gt; 10.0, 11.0, 12.0, 12.5, 12.0, 11.0, 12.0, 16.5, 16.5, 15.5, 16…
## $ Head.W  &lt;dbl&gt; 5.0, 6.5, 6.0, 5.0, 6.0, 5.5, 5.5, 9.0, 9.0, 8.0, 8.0, 10.0, 7…
## $ Neck.G  &lt;dbl&gt; 15.0, 20.0, 17.0, 20.5, 18.0, 16.0, 17.0, 28.0, 27.0, 31.0, 32…
## $ Length  &lt;dbl&gt; 45.0, 47.5, 57.0, 59.5, 62.0, 53.0, 56.0, 67.5, 78.0, 72.0, 77…
## $ Chest.G &lt;dbl&gt; 23.0, 24.0, 27.0, 38.0, 31.0, 26.0, 30.5, 45.0, 49.0, 54.0, 52…
## $ Weight  &lt;int&gt; 65, 70, 74, 142, 121, 80, 108, 344, 371, 416, 432, 348, 476, 4…
## $ Obs.No  &lt;int&gt; 1, 1, 2, 3, 4, 1, 2, 1, 2, 1, 1, 1, 2, 3, 4, 1, 1, 2, 1, 1, 2,…
## $ Name    &lt;fct&gt; Allen, Berta, Berta, Berta, Berta, Clyde, Clyde, Doc, Doc, Qui…</code></pre>
</div>
<div id="bears-data-cleaning" class="section level3">
<h3><span class="header-section-number">2.6.2</span> Bears Data Cleaning</h3>
<p>Notice that we have multiple observations on the same bears. The procedures we have learned so far require observations to be independent of each other. Thus, we'll keep only the first observation on each bear.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Bears_Subset &lt;-<span class="st"> </span>bears <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Obs.No <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)</code></pre></div>
<p>The variables Month and Sex are coded as integers, but it really makes more sense to think of these as categorical variables. Thus, we will convert them to factors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Bears_Subset<span class="op">$</span>Month &lt;-<span class="st"> </span><span class="kw">as.factor</span>(Bears_Subset<span class="op">$</span>Month)
Bears_Subset<span class="op">$</span>Sex &lt;-<span class="st"> </span><span class="kw">as.factor</span>(Bears_Subset<span class="op">$</span>Sex)</code></pre></div>
</div>
<div id="examining-the-subset" class="section level3">
<h3><span class="header-section-number">2.6.3</span> Examining the Subset</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(Bears_Subset)</code></pre></div>
<pre><code>## Rows: 97
## Columns: 12
## $ ID      &lt;int&gt; 39, 41, 43, 45, 48, 69, 83, 91, 179, 241, 253, 274, 280, 394, …
## $ Age     &lt;int&gt; 19, 19, 19, 55, 81, NA, 115, 104, 100, 56, 51, 57, 53, NA, 68,…
## $ Month   &lt;fct&gt; 7, 7, 7, 7, 9, 10, 7, 8, 4, 7, 4, 9, 5, 6, 8, 8, 8, 8, 8, 8, 9…
## $ Sex     &lt;fct&gt; 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1,…
## $ Head.L  &lt;dbl&gt; 10.0, 11.0, 11.0, 16.5, 15.5, 16.0, 17.0, 15.5, 13.0, 15.0, 13…
## $ Head.W  &lt;dbl&gt; 5.0, 6.5, 5.5, 9.0, 8.0, 8.0, 10.0, 6.5, 7.0, 7.5, 8.0, 7.0, 6…
## $ Neck.G  &lt;dbl&gt; 15.0, 20.0, 16.0, 28.0, 31.0, 32.0, 31.5, 22.0, 21.0, 26.5, 27…
## $ Length  &lt;dbl&gt; 45.0, 47.5, 53.0, 67.5, 72.0, 77.0, 72.0, 62.0, 70.0, 73.5, 68…
## $ Chest.G &lt;dbl&gt; 23, 24, 26, 45, 54, 52, 49, 35, 41, 41, 49, 38, 31, 32, 44, 19…
## $ Weight  &lt;int&gt; 65, 70, 80, 344, 416, 432, 348, 166, 220, 262, 360, 204, 144, …
## $ Obs.No  &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
## $ Name    &lt;fct&gt; Allen, Berta, Clyde, Doc, Quincy, Kooch, Charlie, Geraldine, F…</code></pre>
</div>
<div id="examining-the-month-variable" class="section level3">
<h3><span class="header-section-number">2.6.4</span> Examining the Month Variable</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Bears_Subset, <span class="kw">aes</span>(<span class="dt">x=</span>Month)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">color=</span><span class="st">&quot;white&quot;</span>, <span class="dt">fill=</span><span class="st">&quot;lightblue&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>Notice that there are no measurements between December and March, the bears' hibernation season.</p>
</div>
<div id="season-variable" class="section level3">
<h3><span class="header-section-number">2.6.5</span> Season Variable</h3>
<p>When a variable has many categories, it becomes harder to compare the categories. Sometimes, it is helpful to create a new variable with fewer variables by combining categories.</p>
<p>Let's combine the months of April and May into a category called &quot;Spring&quot;, June, July, and August into &quot;Summer&quot;, and &quot;September&quot;, &quot;October&quot;, and &quot;November&quot;, into &quot;Fall&quot;.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Bears_Subset &lt;-<span class="st"> </span>Bears_Subset <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">Season =</span> <span class="kw">ifelse</span>(Month <span class="op">%in%</span><span class="st"> </span><span class="dv">4</span><span class="op">:</span><span class="dv">5</span>, <span class="st">&quot;Spring&quot;</span>,
<span class="kw">ifelse</span>(Month <span class="op">%in%</span><span class="st"> </span><span class="dv">6</span><span class="op">:</span><span class="dv">8</span>, <span class="st">&quot;Summer&quot;</span>, <span class="st">&quot;Fall&quot;</span>)))
Bears_Subset<span class="op">$</span>Season &lt;-<span class="st"> </span><span class="kw">as.factor</span>(Bears_Subset<span class="op">$</span>Season)</code></pre></div>
</div>
<div id="visualizing-season-variable" class="section level3">
<h3><span class="header-section-number">2.6.6</span> Visualizing Season Variable</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Bears_Subset, <span class="kw">aes</span>(<span class="dt">x=</span>Season)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">color=</span><span class="st">&quot;white&quot;</span>, <span class="dt">fill=</span><span class="st">&quot;lightblue&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
</div>
<div id="bears-data-summary" class="section level3">
<h3><span class="header-section-number">2.6.7</span> Bears Data Summary</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(Bears_Subset)</code></pre></div>
<pre><code>##        ID             Age             Month    Sex        Head.L     
##  Min.   : 39.0   Min.   :  8.00   8      :23   1:62   Min.   : 9.00  
##  1st Qu.:525.0   1st Qu.: 17.00   9      :20   2:35   1st Qu.:12.00  
##  Median :579.0   Median : 34.00   10     :14          Median :13.00  
##  Mean   :537.6   Mean   : 42.64   7      :11          Mean   :13.29  
##  3rd Qu.:640.0   3rd Qu.: 57.25   11     : 9          3rd Qu.:14.50  
##  Max.   :911.0   Max.   :177.00   4      : 8          Max.   :18.50  
##                  NA&#39;s   :41       (Other):12                         
##      Head.W           Neck.G          Length         Chest.G     
##  Min.   : 4.000   Min.   :10.00   Min.   :36.00   Min.   :19.00  
##  1st Qu.: 5.000   1st Qu.:17.50   1st Qu.:54.50   1st Qu.:30.00  
##  Median : 6.000   Median :20.00   Median :61.00   Median :34.00  
##  Mean   : 6.364   Mean   :21.03   Mean   :60.41   Mean   :35.93  
##  3rd Qu.: 7.000   3rd Qu.:24.00   3rd Qu.:67.00   3rd Qu.:42.00  
##  Max.   :10.000   Max.   :32.00   Max.   :83.00   Max.   :55.00  
##                                                                  
##      Weight          Obs.No       Name       Season  
##  Min.   : 26.0   Min.   :1   Ian    : 2   Fall  :43  
##  1st Qu.:114.0   1st Qu.:1   Abe    : 1   Spring:14  
##  Median :154.0   Median :1   Addy   : 1   Summer:40  
##  Mean   :187.2   Mean   :1   Albert : 1              
##  3rd Qu.:236.0   3rd Qu.:1   Allen  : 1              
##  Max.   :514.0   Max.   :1   (Other):89              
##                              NA&#39;s   : 2</code></pre>
</div>
<div id="histogram-of-bear-weights" class="section level3">
<h3><span class="header-section-number">2.6.8</span> Histogram of Bear Weights</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Bears_Subset, <span class="kw">aes</span>(<span class="dt">x=</span>Weight)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color=</span><span class="st">&quot;white&quot;</span>, <span class="dt">fill=</span><span class="st">&quot;lightblue&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Weight&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Weights of Bears&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>We see that bears most commonly weigh between 100 and 200 lbs, and the distribution of weights is right-skewed.</p>
</div>
<div id="weight-by-season" class="section level3">
<h3><span class="header-section-number">2.6.9</span> Weight by Season</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Bears_Subset, <span class="kw">aes</span>(<span class="dt">x=</span>Season, <span class="dt">y=</span>Weight)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_jitter</span>() </code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
</div>
<div id="boxplot-of-weight-and-sex" class="section level3">
<h3><span class="header-section-number">2.6.10</span> Boxplot of Weight and Sex</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Bears_Subset, <span class="kw">aes</span>(<span class="dt">y=</span>Weight, <span class="dt">x=</span>Sex)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Sex(1=M, 2=F)&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Weight&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Weight by Sex&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">coord_flip</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>We see that male bears (Category 1) weigh more than female bears on average, and that there is more variability in the weights of male bears than female bears.</p>
</div>
<div id="bears-season-and-sex-model-without-interaction" class="section level3">
<h3><span class="header-section-number">2.6.11</span> Bears: Season and Sex Model without Interaction</h3>
<p><span class="math inline">\(\widehat{\text{Weight}} = b_0+b_1\times\text{I}_{\text{Spring}}+b_2\times\text{I}_{\text{Summer}} + b_3\times\text{I}_{\text{Female}}\)</span></p>
<table>
<thead>
<tr class="header">
<th>Season</th>
<th>Male</th>
<th>Female</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fall</td>
<td><span class="math inline">\(b_0\)</span></td>
<td><span class="math inline">\(b_0 + b_3\)</span></td>
</tr>
<tr class="even">
<td>Spring</td>
<td><span class="math inline">\(b_0 + b_1\)</span></td>
<td><span class="math inline">\(b_0 + b_1+ b_3\)</span></td>
</tr>
<tr class="odd">
<td>Summer</td>
<td><span class="math inline">\(b_0 + b_2\)</span></td>
<td><span class="math inline">\(b_0 + b_2+ b_3\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Model Assumptions</strong>:</p>
<ul>
<li>Allows weights to differ by sex and season.<br />
</li>
<li>Assumes difference between sexes is the same in each season and difference between seasons is the same for each sex.</li>
</ul>
</div>
<div id="bears-season-and-sex-model-output" class="section level3">
<h3><span class="header-section-number">2.6.12</span> Bears Season and Sex Model Output</h3>
<p>Let's model weights of male and female bears individually by season.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Bears_M_Season_Sex &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Bears_Subset, Weight<span class="op">~</span>Season <span class="op">+</span><span class="st"> </span>Sex)
<span class="kw">summary</span>(Bears_M_Season_Sex)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Weight ~ Season + Sex, data = Bears_Subset)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -186.73  -76.56  -17.32   63.44  287.27 
## 
## Coefficients:
##              Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)    226.73      18.14  12.500 &lt; 0.0000000000000002 ***
## SeasonSpring   -25.54      33.56  -0.761              0.44856    
## SeasonSummer   -28.17      23.79  -1.184              0.23939    
## Sex2           -67.24      23.06  -2.916              0.00445 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 108.3 on 93 degrees of freedom
## Multiple R-squared:  0.1024, Adjusted R-squared:  0.07343 
## F-statistic: 3.536 on 3 and 93 DF,  p-value: 0.01774</code></pre>
</div>
<div id="predictions-using-season-and-sex" class="section level3">
<h3><span class="header-section-number">2.6.13</span> Predictions using Season and Sex</h3>
<p><span class="math inline">\(\widehat{\text{Weight}} = 226.73-25.54 \times\text{I}_{\text{Spring}}-28.17\times\text{I}_{\text{Summer}} -67.24\times\text{I}_{\text{Female}}\)</span></p>
<table style="width:40%;">
<colgroup>
<col width="9%" />
<col width="15%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Male</th>
<th>Female</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fall</td>
<td>226.73 - 25.54(0) - 28.17(0) -67.24(0)=226.73</td>
<td>226.73 - 25.54(0) - 28.17(0) -67.24(1)=159.59</td>
</tr>
<tr class="even">
<td>Spring</td>
<td>226.73 - 25.54(1) - 28.17(0) -67.24(0)=201.19</td>
<td>226.73 - 25.54(1) - 28.17(0) -67.24(1)=133.95</td>
</tr>
<tr class="odd">
<td>Summer</td>
<td>226.73 - 25.54(0) - 28.17(1) -67.24(0)=198.55</td>
<td>226.73 - 25.54(0) - 28.17(1) -67.24(1)=131.32</td>
</tr>
</tbody>
</table>
</div>
<div id="weight-using-season-and-sex-model-interpretations" class="section level3">
<h3><span class="header-section-number">2.6.14</span> Weight using Season and Sex Model Interpretations</h3>
<p><span class="math inline">\(\widehat{\text{Weight}} = 226.73-25.54 \times\text{I}_{\text{Spring}}-28.17\times\text{I}_{\text{Summer}} -67.24\times\text{I}_{\text{Female}}\)</span></p>
<p>Note that fall and male are treated as the &quot;baseline&quot; levels in this model.</p>
<ul>
<li><p>On average, male bears are expected to weigh 226.73 lbs in the fall.</p></li>
<li><p>On average, bears of the same sex are expected to weigh 25.54 lbs less in the spring than in the fall.</p></li>
<li><p>On average, bears of the same sex are expected to weigh 28.17 lbs less in the summer than in the fall.</p></li>
<li><p>On average, female bears are expected to weigh 67.24 lbs than male bears, in the same season.</p></li>
</ul>
<p>The model with season and sex explains about 10% of the variation in bear weights.</p>
</div>
<div id="season-and-sex-with-interaction" class="section level3">
<h3><span class="header-section-number">2.6.15</span> Season and Sex with Interaction</h3>
<p><span class="math display">\[\widehat{\text{Weight}} = b_0 + b_1 \times\text{I}_{\text{Spring}} + b_2\times\text{I}_{\text{Summer}} +b_3\times\text{I}_{\text{Female}}\\ +b_4\times\text{I}_{\text{Spring}}\text{I}_{\text{Female}} +b_5\times\text{I}_{\text{Summer}}\text{I}_{\text{Female}}\]</span></p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Male</th>
<th>Female</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fall</td>
<td><span class="math inline">\(b_0\)</span></td>
<td>b_0+b_3</td>
</tr>
<tr class="even">
<td>Spring</td>
<td><span class="math inline">\(b_0+b_1\)</span></td>
<td><span class="math inline">\(b_0+b_1 +b_3+b_4\)</span></td>
</tr>
<tr class="odd">
<td>Summer</td>
<td><span class="math inline">\(b_0+b_2\)</span></td>
<td><span class="math inline">\(b_0+b_2+b_3+b_5\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Model Assumptions</strong>:</p>
<ul>
<li>Allows for differences between seasons and sexes.<br />
</li>
<li>Allows for differences between sexes to vary between seasons and difference between seasons to vary between sexes.</li>
</ul>
<p><span class="math inline">\(b_4\)</span> and <span class="math inline">\(b_5\)</span> are called <strong>interaction effects</strong>.</p>
</div>
<div id="bears-season-and-sex-interaction-model" class="section level3">
<h3><span class="header-section-number">2.6.16</span> Bears Season and Sex Interaction Model</h3>
<p>To fit an interaction model in R, use <code>*</code> instead of <code>+</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Bears_M_Season_Sex_Int &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Bears_Subset, Weight<span class="op">~</span>Season <span class="op">*</span><span class="st"> </span>Sex)
<span class="kw">summary</span>(Bears_M_Season_Sex_Int)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Weight ~ Season * Sex, data = Bears_Subset)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -181.14  -73.14  -13.07   58.81  292.86 
## 
## Coefficients:
##                   Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)         221.14      20.28  10.905 &lt;0.0000000000000002 ***
## SeasonSpring        -14.00      45.99  -0.304               0.762    
## SeasonSummer        -17.95      29.49  -0.608               0.544    
## Sex2                -50.07      35.54  -1.409               0.162    
## SeasonSpring:Sex2   -29.08      68.34  -0.425               0.672    
## SeasonSummer:Sex2   -30.41      50.73  -0.599               0.550    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 109.2 on 91 degrees of freedom
## Multiple R-squared:  0.1064, Adjusted R-squared:  0.0573 
## F-statistic: 2.167 on 5 and 91 DF,  p-value: 0.06458</code></pre>
</div>
<div id="predictions-for-season-and-sex-interaction-model" class="section level3">
<h3><span class="header-section-number">2.6.17</span> Predictions for Season and Sex Interaction Model</h3>
<p><span class="math display">\[\widehat{\text{Weight}} = b_0 + b_1 \times\text{I}_{\text{Spring}} + b_2\times\text{I}_{\text{Summer}} +b_3\times\text{I}_{\text{Female}}\\ +b_4\times\text{I}_{\text{Spring}}\text{I}_{\text{Female}} +b_5\times\text{I}_{\text{Summer}}\text{I}_{\text{Female}}\]</span></p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{Weight}} &amp;= 221.14 -14.00 \times\text{I}_{\text{Spring}} -17.95\times\text{I}_{\text{Summer}} -50.07\times\text{I}_{\text{Female}} \\
&amp;-29.08\times\text{I}_{\text{Spring}}\text{I}_{\text{Female}} -30.41\times\text{I}_{\text{Summer}}\text{I}_{\text{Female}}
\end{aligned}
\]</span></p>
<table style="width:40%;">
<colgroup>
<col width="9%" />
<col width="15%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Male</th>
<th>Female</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fall</td>
<td>221.14 -14.00(0) -17.95(0) -50.07(0) -29.08(0)(0) -30.41(0)(0)=221.14</td>
<td>221.14 -14.00(0) -17.95(0) -50.07(1) -29.08(0)(1) -30.41(0)(1) =171.07</td>
</tr>
<tr class="even">
<td>Spring</td>
<td>221.14 -14.00(1) -17.95(0) -50.07(0) -29.08(1)(0) -30.41(0)(0) =207.14</td>
<td>211.375 + 8.01221.14 -14.00(1) -17.95(0) -50.07(1) -29.08(1)(1) -30.41(0)(1)=128.00</td>
</tr>
<tr class="odd">
<td>Summer</td>
<td>221.14 -14.00(0) -17.95(1) -50.07(0) -29.08(0)(0) -30.41(1)(0) =203.19</td>
<td>221.14 -14.00(0) -17.95(1) -50.07(1) -29.08(0)(1) -30.41(1)(1) =122.71</td>
</tr>
</tbody>
</table>
</div>
<div id="season-and-sex-interaction-model-interpretations" class="section level3">
<h3><span class="header-section-number">2.6.18</span> Season and Sex Interaction Model Interpretations</h3>
<p><span class="math display">\[\widehat{\text{Weight}} = b_0 + b_1 \times\text{I}_{\text{Spring}} + b_2\times\text{I}_{\text{Summer}} +b_3\times\text{I}_{\text{Female}}\\ +b_4\times\text{I}_{\text{Spring}}\text{I}_{\text{Female}} +b_5\times\text{I}_{\text{Summer}}\text{I}_{\text{Female}}\]</span></p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Male</th>
<th>Female</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fall</td>
<td><span class="math inline">\(b_0\)</span></td>
<td><span class="math inline">\(b_0+b_3\)</span></td>
</tr>
<tr class="even">
<td>Spring</td>
<td><span class="math inline">\(b_0+b_1\)</span></td>
<td><span class="math inline">\(b_0+b_1 +b_3+b_4\)</span></td>
</tr>
<tr class="odd">
<td>Summer</td>
<td><span class="math inline">\(b_0+b_2\)</span></td>
<td><span class="math inline">\(b_0+b_2+b_3+b_5\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><span class="math inline">\(b_0\)</span> represents expected weight of male bear in fall<br />
</li>
<li><span class="math inline">\(b_1\)</span> represents difference between expected male bear weight in spring, compared to fall<br />
</li>
<li><span class="math inline">\(b_2\)</span> represents difference between expected male bear weight in summer, compared to fall<br />
</li>
<li><span class="math inline">\(b_3\)</span> represents difference between expected female bear weight, compared to male bear weight in fall<br />
</li>
<li><span class="math inline">\(b_4\)</span> represents difference in expected weights between the sexes in the spring, compared to the difference in the fall<br />
</li>
<li><span class="math inline">\(b_5\)</span> represents difference in expected weights between the sexes in the summer, compared to the difference in the fall</li>
</ul>
</div>
<div id="interpretations-for-season-and-sex-interaction-model" class="section level3">
<h3><span class="header-section-number">2.6.19</span> Interpretations for Season and Sex Interaction Model</h3>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{Weight}} &amp;= 221.14 -14.00 \times\text{I}_{\text{Spring}} -17.95\times\text{I}_{\text{Summer}} -50.07\times\text{I}_{\text{Female}} \\
&amp;-29.08\times\text{I}_{\text{Spring}}\text{I}_{\text{Female}} -30.41\times\text{I}_{\text{Summer}}\text{I}_{\text{Female}}
\end{aligned}
\]</span></p>
<ul>
<li>On average, male bears are expected to weigh 221.14 lbs in the fall.<br />
</li>
<li>On average male bears are expected to weigh 14 lbs less in the spring than in the fall.<br />
</li>
<li>On average, male bears are expected to weigh 17.95 lbs less in the summer than in the fall.<br />
</li>
<li>On average, female bears are expected to weigh 50.07 lbs less than male bears in the fall.<br />
</li>
<li>On average, the female bears are expected to weigh 29.08 lbs. less relative to male bears in the spring, compared to the expected difference the fall. Thus, female bears are expected to weigh 50.07 + 29.08 = 79.17 lbs less than male bears in the spring.<br />
</li>
<li>On average, female bears are expected to weigh 30.41 lbs less, relative to male bears in the summer, compared to the expected difference in the fall. Thus, female bears are expected to weigh <span class="math inline">\(50.07 + 30.41 = 80.48\)</span> lbs less than male bears in the summer.</li>
</ul>
<p>The interaction model explains about 10.6% of the variation in bear weights.</p>
</div>
<div id="predicting-new-observations-in-r" class="section level3">
<h3><span class="header-section-number">2.6.20</span> Predicting New Observations in R</h3>
<p>We can calculate predictions directly in R by putting the new data in a data.frame and calling the <code>predict()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Season &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Fall&quot;</span>, <span class="st">&quot;Fall&quot;</span>, <span class="st">&quot;Spring&quot;</span>, <span class="st">&quot;Spring&quot;</span>, <span class="st">&quot;Summer&quot;</span>, <span class="st">&quot;Summer&quot;</span>)
Sex &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">2</span>))
NewBears &lt;-<span class="st"> </span><span class="kw">data.frame</span>(Season, Sex)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(Bears_M_Season_Sex, <span class="dt">newdata=</span>NewBears)</code></pre></div>
<pre><code>##        1        2        3        4        5        6 
## 226.7290 159.4900 201.1909 133.9520 198.5586 131.3197</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(Bears_M_Season_Sex_Int, <span class="dt">newdata=</span>NewBears)</code></pre></div>
<pre><code>##        1        2        3        4        5        6 
## 221.1379 171.0714 207.1429 128.0000 203.1923 122.7143</code></pre>
</div>
</div>
<div id="section-2.7-interaction-models-with-categorical-and-quantitative-variables" class="section level2">
<h2><span class="header-section-number">2.7</span> Section 2.7 Interaction Models with Categorical and Quantitative Variables</h2>
<div id="summary-of-bears-dataset" class="section level3">
<h3><span class="header-section-number">2.7.1</span> Summary of Bears Dataset</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(Bears_Subset)</code></pre></div>
<pre><code>##        ID             Age             Month    Sex        Head.L     
##  Min.   : 39.0   Min.   :  8.00   8      :23   1:62   Min.   : 9.00  
##  1st Qu.:525.0   1st Qu.: 17.00   9      :20   2:35   1st Qu.:12.00  
##  Median :579.0   Median : 34.00   10     :14          Median :13.00  
##  Mean   :537.6   Mean   : 42.64   7      :11          Mean   :13.29  
##  3rd Qu.:640.0   3rd Qu.: 57.25   11     : 9          3rd Qu.:14.50  
##  Max.   :911.0   Max.   :177.00   4      : 8          Max.   :18.50  
##                  NA&#39;s   :41       (Other):12                         
##      Head.W           Neck.G          Length         Chest.G     
##  Min.   : 4.000   Min.   :10.00   Min.   :36.00   Min.   :19.00  
##  1st Qu.: 5.000   1st Qu.:17.50   1st Qu.:54.50   1st Qu.:30.00  
##  Median : 6.000   Median :20.00   Median :61.00   Median :34.00  
##  Mean   : 6.364   Mean   :21.03   Mean   :60.41   Mean   :35.93  
##  3rd Qu.: 7.000   3rd Qu.:24.00   3rd Qu.:67.00   3rd Qu.:42.00  
##  Max.   :10.000   Max.   :32.00   Max.   :83.00   Max.   :55.00  
##                                                                  
##      Weight          Obs.No       Name       Season  
##  Min.   : 26.0   Min.   :1   Ian    : 2   Fall  :43  
##  1st Qu.:114.0   1st Qu.:1   Abe    : 1   Spring:14  
##  Median :154.0   Median :1   Addy   : 1   Summer:40  
##  Mean   :187.2   Mean   :1   Albert : 1              
##  3rd Qu.:236.0   3rd Qu.:1   Allen  : 1              
##  Max.   :514.0   Max.   :1   (Other):89              
##                              NA&#39;s   : 2</code></pre>
</div>
<div id="histogram-of-bear-ages" class="section level3">
<h3><span class="header-section-number">2.7.2</span> Histogram of Bear Ages</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Bears_Subset, <span class="kw">aes</span>(<span class="dt">x=</span>Age)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color=</span><span class="st">&quot;white&quot;</span>, <span class="dt">fill=</span><span class="st">&quot;lightblue&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Age (in months)&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Ages of Bears (in months)&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
</div>
<div id="bears-with-missing-ages" class="section level3">
<h3><span class="header-section-number">2.7.3</span> Bears with Missing Ages</h3>
<p>Recall that 41 bears had missing ages. They will be ignored if we use age in our model. To see how this might impact predicted weights, let's look at how weights compare for bears with and without missing ages.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Bears_Subset, <span class="kw">aes</span>(<span class="dt">x=</span><span class="kw">is.na</span>(Age), <span class="dt">y=</span>Weight)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">coord_flip</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>Bears with missing ages do not seem to be systematically different than those whose ages are recorded, with respect to weight, so the missing ages should not cause too much concern with out model results.</p>
</div>
<div id="boxplot-of-weight-and-sex-1" class="section level3">
<h3><span class="header-section-number">2.7.4</span> Boxplot of Weight and Sex</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Bears_Subset, <span class="kw">aes</span>(<span class="dt">y=</span>Weight, <span class="dt">x=</span>Sex)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Sex(1=M, 2=F)&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Weight in lbs&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Weight by Sex&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">coord_flip</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
</div>
<div id="boxplot-of-age-and-sex" class="section level3">
<h3><span class="header-section-number">2.7.5</span> Boxplot of Age and Sex</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Bears_Subset, <span class="kw">aes</span>(<span class="dt">y=</span>Age, <span class="dt">x=</span>Sex)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Sex(1=M, 2=F)&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Age in Months&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Age by Sex&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">coord_flip</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
<p>The median age for female bears is older than for male bears. There are 2 male bears that are much older than any others.</p>
</div>
<div id="scatterplot-of-age-and-weight" class="section level3">
<h3><span class="header-section-number">2.7.6</span> Scatterplot of Age and Weight</h3>
<p><img src="_main_files/figure-html/unnamed-chunk-85-1.png" width="768" /></p>
<p>We see that there is a positive, roughly linear, relationship between age and weight.</p>
<p>We should note that this linear trend is not likely to continue outside the range of our observed ages.</p>
</div>
<div id="bears-age-and-sex-model" class="section level3">
<h3><span class="header-section-number">2.7.7</span> Bears: Age and Sex Model</h3>
<p><span class="math inline">\(\widehat{\text{Weight}}= b_0+ b_1 \times\text{Age}+ b_2\times\text{I}_{Female}\)</span></p>
<table>
<thead>
<tr class="header">
<th>Sex</th>
<th>Pred. Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>M</td>
<td><span class="math inline">\(b_0 + b_1 \times\text{Age}\)</span></td>
</tr>
<tr class="even">
<td>F</td>
<td><span class="math inline">\((b_0 + b_2) + b_1 \times\text{Age}\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Model Assumptions:</strong></p>
<ul>
<li>Assumes weight increases linearly with age<br />
</li>
<li>Allows for differences in expected weight for male and female bears of same age<br />
</li>
<li>Assumes male and female bears gain weight at the same rate as they age</li>
</ul>
</div>
<div id="constant-slope-model-for-bears" class="section level3">
<h3><span class="header-section-number">2.7.8</span> Constant Slope Model for Bears</h3>
<p><img src="_main_files/figure-html/unnamed-chunk-87-1.png" width="768" /></p>
</div>
<div id="bears-age-and-sex-model-output" class="section level3">
<h3><span class="header-section-number">2.7.9</span> Bears Age and Sex Model Output</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Bears_M_Age_Sex &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Bears_Subset, Weight <span class="op">~</span><span class="st"> </span>Age <span class="op">+</span><span class="st"> </span>Sex)
<span class="kw">summary</span>(Bears_M_Age_Sex)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Weight ~ Age + Sex, data = Bears_Subset)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -164.194  -48.483   -3.723   27.766  188.684 
## 
## Coefficients:
##             Estimate Std. Error t value           Pr(&gt;|t|)    
## (Intercept)  82.6049    16.4019   5.036 0.0000058437067215 ***
## Age           2.9242     0.2914  10.035 0.0000000000000744 ***
## Sex2        -79.8967    20.1416  -3.967            0.00022 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 71.33 on 53 degrees of freedom
##   (41 observations deleted due to missingness)
## Multiple R-squared:  0.6679, Adjusted R-squared:  0.6554 
## F-statistic: 53.29 on 2 and 53 DF,  p-value: 0.0000000000002061</code></pre>
</div>
<div id="predicted-bear-weights-from-age-and-sex-model" class="section level3">
<h3><span class="header-section-number">2.7.10</span> Predicted Bear Weights from Age and Sex Model</h3>
<p><span class="math inline">\(\widehat{\text{Weight}}= 82.60 + 2.92 \times\text{Age} - 79.90\times\text{I}_{Female}\)</span></p>
<p>Suppose Sally and Yogi are 25 month old bears, Sally is a female, Yogi a male.</p>
<p>Sally's Predicted Weight:</p>
<p><span class="math inline">\(\widehat{\text{Weight}}= 82.60 + 2.920 \times 25 -78.90\times 1 \approx 75.8 \text{ lbs.}\)</span></p>
<p>Yogi's Predicted Weight:</p>
<p><span class="math inline">\(\widehat{\text{Weight}}= 82.60 + 2.920 \times 25 -78.90\times 0 \approx 155.7 \text{ lbs.}\)</span></p>
</div>
<div id="age-and-sex-model-for-male-and-female-bears" class="section level3">
<h3><span class="header-section-number">2.7.11</span> Age and Sex Model for Male and Female Bears</h3>
<p>The interaction model allows for different intercepts, but assumes that the average monthly weight increase is the same for male and female bears.</p>
<p><span class="math inline">\(\widehat{\text{Weight}}= 82.60 + 2.92 \times\text{Age} - 79.90\times\text{I}_{Female}\)</span></p>
<p>Male Bears: <span class="math display">\[
\widehat{\text{Weight}}= 82.60 + 2.92 \times\text{Age}
\]</span></p>
<p>Female Bears: <span class="math display">\[
\widehat{\text{Weight}}= (82.60 -79.90) + (2.92)\times\text{Age} \\
= 2.7+2.92\times Age
\]</span></p>
</div>
<div id="bears-predictions-with-predict" class="section level3">
<h3><span class="header-section-number">2.7.12</span> Bears Predictions with <code>predict</code></h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Sex &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))
Age &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">25</span>, <span class="dv">25</span>)
NewBears &lt;-<span class="st"> </span><span class="kw">data.frame</span>(Age, Sex)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(Bears_M_Age_Sex, <span class="dt">newdata=</span>NewBears)</code></pre></div>
<pre><code>##         1         2 
## 155.71061  75.81394</code></pre>
</div>
<div id="age-and-sex-model-interpretations" class="section level3">
<h3><span class="header-section-number">2.7.13</span> Age and Sex Model Interpretations</h3>
<ul>
<li><p>For bears of the same sex, weight is expected to increase by 2.92 lbs. each month.</p></li>
<li><p>On average, a female bear is expected to weigh 79.90 lbs less than a male bear of the same age.</p></li>
<li><p>The intercept <span class="math inline">\(b_0=82.60\)</span> represents the expected weight of a male bear at birth. We should treat this interpretation with caution, since all bears in the dataset were at least 8 months old.</p></li>
</ul>
<p>Approximately 67% of the variation in bear weights is explained by the model using age and sex as explanatory variables.</p>
</div>
<div id="bears-age-and-sex-model-with-interaction" class="section level3">
<h3><span class="header-section-number">2.7.14</span> Bears Age and Sex Model with Interaction</h3>
<p><span class="math inline">\(\widehat{\text{Weight}}= b_0+ b_1 \times\text{Age}+ b_2\times\text{I}_{Female} + b_3\times\text{Age}\times\text{I}_{Female}\)</span></p>
<table>
<thead>
<tr class="header">
<th>Sex</th>
<th>Pred. Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>M</td>
<td><span class="math inline">\(b_0 + b_1 \times\text{Age}\)</span></td>
</tr>
<tr class="even">
<td>F</td>
<td><span class="math inline">\((b_0 + b_2) + (b_1 + b_3) \times\text{Age}\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Model Assumptions:</strong></p>
<ul>
<li>Assumes weight increases linearly with age<br />
</li>
<li>Allows for differences in expected weight for male and female bears of same age<br />
</li>
<li>Allows male and female bears to gain weight at different rates as they age</li>
</ul>
</div>
<div id="bears-age-and-sex-interaction-model" class="section level3">
<h3><span class="header-section-number">2.7.15</span> Bears Age and Sex Interaction Model</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Bears_Subset, <span class="kw">aes</span>(<span class="dt">x=</span>Age, <span class="dt">y=</span>Weight, <span class="dt">color=</span>Sex)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_smooth</span>(<span class="dt">method=</span><span class="st">&quot;lm&quot;</span>, <span class="dt">se=</span><span class="ot">FALSE</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-91-1.png" width="672" /></p>
</div>
<div id="summary-for-age-sex-interaction-model" class="section level3">
<h3><span class="header-section-number">2.7.16</span> Summary for Age-Sex Interaction Model</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Bears_M_Age_Sex_Int &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Bears_Subset, Weight<span class="op">~</span><span class="st"> </span>Age<span class="op">*</span>Sex)
<span class="kw">summary</span>(Bears_M_Age_Sex_Int)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Weight ~ Age * Sex, data = Bears_Subset)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -207.583  -38.854   -9.574   23.905  174.802 
## 
## Coefficients:
##             Estimate Std. Error t value          Pr(&gt;|t|)    
## (Intercept)  70.4322    17.7260   3.973          0.000219 ***
## Age           3.2381     0.3435   9.428 0.000000000000765 ***
## Sex2        -31.9574    35.0314  -0.912          0.365848    
## Age:Sex2     -1.0350     0.6237  -1.659          0.103037    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 70.18 on 52 degrees of freedom
##   (41 observations deleted due to missingness)
## Multiple R-squared:  0.6846, Adjusted R-squared:  0.6664 
## F-statistic: 37.62 on 3 and 52 DF,  p-value: 0.0000000000004552</code></pre>
</div>
<div id="predictions-from-interaction-model-for-bears" class="section level3">
<h3><span class="header-section-number">2.7.17</span> Predictions from Interaction Model for Bears</h3>
<p><span class="math inline">\(\widehat{\text{Weight}}= 70.43 + 3.24 \times\text{Age}- 31.96\times\text{I}_{Female} -1.04\times\text{Age}\times\text{I}_{Female}\)</span></p>
<p>Suppose Sally and Yogi are 25 month old bears, Sally is a female, Yogi a male.</p>
<p>Sally's Predicted Weight:</p>
<p><span class="math inline">\(\widehat{\text{Weight}}= 70.43+ 3.24 \times 25- 31.96\times1 -1.04\times25\times1 \approx 93.55 \text{ lbs.}\)</span></p>
<p>Yogi's Predicted Weight:</p>
<p><span class="math inline">\(\widehat{\text{Weight}}= 70.43+ 3.24 \times 25- 31.96\times0 -1.04\times25\times0 \approx 151.38 \text{ lbs.}\)</span></p>
</div>
<div id="interaction-model-for-male-and-female-bears" class="section level3">
<h3><span class="header-section-number">2.7.18</span> Interaction Model for Male and Female Bears</h3>
<p>The interaction model allow for different intercepts and slopes between male and female bears.</p>
<p><span class="math inline">\(\widehat{\text{Weight}}= 70.43 + 3.24 \times\text{Age}- 31.96\times\text{I}_{Female} -1.04\times\text{Age}\times\text{I}_{Female}\)</span></p>
<p>Male Bears: <span class="math display">\[
\widehat{\text{Weight}}= 70.43 + 3.24 \times\text{Age}
\]</span></p>
<p>Female Bears: <span class="math display">\[
\widehat{\text{Weight}}= (70.43 -31.96) + (3.24 -1.04)\times\text{Age} \\
= 38.46-2.20\times Age
\]</span></p>
</div>
<div id="bears-interaction-model-predictions-with-predict" class="section level3">
<h3><span class="header-section-number">2.7.19</span> Bears Interaction Model Predictions with <code>predict</code></h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Sex &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))
Age &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">25</span>, <span class="dv">25</span>)
NewBears &lt;-<span class="st"> </span><span class="kw">data.frame</span>(Age, Sex)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(Bears_M_Age_Sex_Int, <span class="dt">newdata=</span>NewBears)</code></pre></div>
<pre><code>##         1         2 
## 151.38566  93.55306</code></pre>
</div>
<div id="interpretations-for-age-and-sex-model-with-interaction" class="section level3">
<h3><span class="header-section-number">2.7.20</span> Interpretations for Age and Sex Model with Interaction</h3>
<p><span class="math inline">\(\widehat{\text{Weight}}= b_0+ b_1 \times\text{Age}+ b_2\times\text{I}_{Female} + b_3\times\text{Age}\times\text{I}_{Female}\)</span></p>
<table>
<thead>
<tr class="header">
<th>Sex</th>
<th>Pred. Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>M</td>
<td><span class="math inline">\(b_0 + b_1 \times\text{Age}\)</span></td>
</tr>
<tr class="even">
<td>F</td>
<td><span class="math inline">\((b_0 + b_2) + (b_1 + b_3) \times\text{Age}\)</span></td>
</tr>
</tbody>
</table>
<p>Interpretations:<br />
<span class="math inline">\(b_0\)</span>: expected weight of a male bear at birth (caution:extrapolation)<br />
<span class="math inline">\(b_1\)</span>: expected weight gain per month for male bears<br />
<span class="math inline">\(b_2\)</span>: expected difference in weight between female and male bears at birth (caution:extrapolation)<br />
<span class="math inline">\(b_3\)</span>: expected difference in monthly weight gain for female bears, compared to male bears</p>
</div>
<div id="bears-weight-model-considerations" class="section level3">
<h3><span class="header-section-number">2.7.21</span> Bears Weight Model Considerations</h3>
<ul>
<li><p><span class="math inline">\(R^2\)</span> increased from 0.67 to 0.68 when the interaction term is added. This is a relatively small increase, so we might question whether the interaction term is needed.</p></li>
<li><p>The constant slope model allows us to combine information across sexes to estimate the expected slope. The interaction model treats the two sexes completely separately, thus has less information to use for each estimate.</p></li>
<li><p>Which model is preferable is not clear. In addition to the data, we should consider other relevent information. Do experts who study bears believe it is reasonable to assume that male and female bears grow at the same rate per month?</p></li>
<li><p>While the models yield drastically different predictions for very young bears, the differences are not as big for bear 8 months or older. Regardless of model we use, we should be careful about making predictions for bears that are younger or older than those that we have data on.</p></li>
</ul>
</div>
<div id="bears-weight-model-considerations-continued" class="section level3">
<h3><span class="header-section-number">2.7.22</span> Bears Weight Model Considerations (continued)</h3>
<p>Both of these models contain assumptions that are probably unrealistic</p>
<ul>
<li><p>Both models assume that bears of the same sex gain weight linearly with age.</p></li>
<li><p>A more realistic model might assume that bears gain weight more quickly when they are younger, and that the rate of growth slows once they reach adulthood.</p></li>
<li><p>Are there variables not included in the model that might be predictive of a bear's weight?</p></li>
</ul>
<p>Of course there is no statistical model that perfectly describes expected weight gain of bears. The question is whether we can find a model that provides an approximation that is reasonable enough to draw conclusions from.</p>
<p>As statistician George Box famously said,</p>
<p><em>&quot;All models are wrong, but some are useful.&quot;</em></p>
</div>
</div>
<div id="section-2.8-interaction-models-with-quantitative-variables" class="section level2">
<h2><span class="header-section-number">2.8</span> Section 2.8 Interaction Models with Quantitative Variables</h2>
<div id="cars-dataset" class="section level3">
<h3><span class="header-section-number">2.8.1</span> 2015 Cars Dataset</h3>
<p>We consider data from the Kelly Blue Book, pertaining to new cars, released in 2015. We'll investigate the relationship between price, length, and time it takes to accelerate from 0 to 60 mph.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(Cars2015)
<span class="kw">glimpse</span>(Cars2015)</code></pre></div>
<pre><code>## Rows: 110
## Columns: 20
## $ Make      &lt;fct&gt; Chevrolet, Hyundai, Kia, Mitsubishi, Nissan, Dodge, Chevrole…
## $ Model     &lt;fct&gt; Spark, Accent, Rio, Mirage, Versa Note, Dart, Cruze LS, 500L…
## $ Type      &lt;fct&gt; Hatchback, Hatchback, Sedan, Hatchback, Hatchback, Sedan, Se…
## $ LowPrice  &lt;dbl&gt; 12.270, 14.745, 13.990, 12.995, 14.180, 16.495, 16.170, 19.3…
## $ HighPrice &lt;dbl&gt; 25.560, 17.495, 18.290, 15.395, 17.960, 23.795, 25.660, 24.6…
## $ Drive     &lt;fct&gt; FWD, FWD, FWD, FWD, FWD, FWD, FWD, FWD, FWD, FWD, FWD, AWD, …
## $ CityMPG   &lt;int&gt; 30, 28, 28, 37, 31, 23, 24, 24, 28, 30, 27, 27, 25, 27, 30, …
## $ HwyMPG    &lt;int&gt; 39, 37, 36, 44, 40, 35, 36, 33, 38, 35, 33, 36, 36, 37, 39, …
## $ FuelCap   &lt;dbl&gt; 9.0, 11.4, 11.3, 9.2, 10.9, 14.2, 15.6, 13.1, 12.4, 11.1, 11…
## $ Length    &lt;int&gt; 145, 172, 172, 149, 164, 184, 181, 167, 179, 154, 156, 180, …
## $ Width     &lt;int&gt; 63, 67, 68, 66, 67, 72, 71, 70, 72, 67, 68, 69, 70, 68, 69, …
## $ Wheelbase &lt;int&gt; 94, 101, 101, 97, 102, 106, 106, 103, 104, 99, 98, 104, 104,…
## $ Height    &lt;int&gt; 61, 57, 57, 59, 61, 58, 58, 66, 58, 59, 58, 58, 57, 58, 59, …
## $ UTurn     &lt;int&gt; 34, 37, 37, 32, 37, 38, 38, 37, 39, 34, 35, 38, 37, 36, 37, …
## $ Weight    &lt;int&gt; 2345, 2550, 2575, 2085, 2470, 3260, 3140, 3330, 2990, 2385, …
## $ Acc030    &lt;dbl&gt; 4.4, 3.7, 3.5, 4.4, 4.0, 3.4, 3.7, 3.9, 3.4, 3.9, 3.9, 3.7, …
## $ Acc060    &lt;dbl&gt; 12.8, 10.3, 9.5, 12.1, 10.9, 9.3, 9.8, 9.5, 9.2, 10.8, 11.1,…
## $ QtrMile   &lt;dbl&gt; 19.4, 17.8, 17.3, 19.0, 18.2, 17.2, 17.6, 17.4, 17.1, 18.3, …
## $ PageNum   &lt;int&gt; 123, 148, 163, 188, 196, 128, 119, 131, 136, 216, 179, 205, …
## $ Size      &lt;fct&gt; Small, Small, Small, Small, Small, Small, Small, Small, Smal…</code></pre>
</div>
<div id="car-price-and-acceleration-time" class="section level3">
<h3><span class="header-section-number">2.8.2</span> Car Price and Acceleration Time</h3>
<p><code>LowPrice</code> represents the price of a standard (non-luxury) model of a car. <code>Acc060</code> represents time it takes to accelerate from 0 to 60 mph.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(Cars2015)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">CarsA060 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data=</span>Cars2015, <span class="kw">aes</span>(<span class="dt">x=</span>Acc060, <span class="dt">y=</span>LowPrice)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() 
CarsA060</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-97-1.png" width="672" /></p>
</div>
<div id="length-and-sale-price" class="section level3">
<h3><span class="header-section-number">2.8.3</span> Length and Sale Price</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Cars2015, <span class="kw">aes</span>(<span class="dt">x=</span>Length, <span class="dt">y=</span>LowPrice)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;length in inches&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-98-1.png" width="672" /></p>
</div>
<div id="relationship-between-acc060-and-length" class="section level3">
<h3><span class="header-section-number">2.8.4</span> Relationship between Acc060 and Length</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>Cars2015, <span class="kw">aes</span>(<span class="dt">x=</span>Length, <span class="dt">y=</span>Acc060)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() </code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-99-1.png" width="672" /></p>
<p>Lack of correlation among explanatory variables is a good thing. If explanatory variables are highly correlated, then using them together is unlikely to perform much better than using one or the other. In fact, it can cause problems, as we'll see later.</p>
</div>
<div id="modeling-price-using-acc060" class="section level3">
<h3><span class="header-section-number">2.8.5</span> Modeling Price using Acc060</h3>
<p><span class="math inline">\(\widehat{Price} = b_0 + b_1\times\text{Acc. Time}\)</span></p>
<ul>
<li>Model assumes expected price is a linear function of acceleration time.</li>
</ul>
<p>Parameter Interpretations:</p>
<p><span class="math inline">\(b_0\)</span> represents intercept of regression line, i.e. expected price of a car that can accelerate from 0 to 60 mph in no time. This is not a meaningful interpretation in context.</p>
<p><span class="math inline">\(b_1\)</span> represents slope of regression line, i.e. expected change in price for each additional second it takes to accelerate from 0 to 60 mph.</p>
</div>
<div id="modeling-for-car-price-and-acceleration" class="section level3">
<h3><span class="header-section-number">2.8.6</span> Modeling for Car Price and Acceleration</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Cars_M_A060 &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Cars2015, LowPrice<span class="op">~</span>Acc060)
<span class="kw">summary</span>(Cars_M_A060)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = LowPrice ~ Acc060, data = Cars2015)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -29.512  -6.544  -1.265   4.759  27.195 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)  89.9036     5.0523   17.79 &lt;0.0000000000000002 ***
## Acc060       -7.1933     0.6234  -11.54 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.71 on 108 degrees of freedom
## Multiple R-squared:  0.5521, Adjusted R-squared:  0.548 
## F-statistic: 133.1 on 1 and 108 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
<div id="price-and-a060-regression-line" class="section level3">
<h3><span class="header-section-number">2.8.7</span> Price and A060 Regression Line</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">CarsA060 <span class="op">+</span><span class="st"> </span><span class="kw">stat_smooth</span>(<span class="dt">method=</span><span class="st">&quot;lm&quot;</span>, <span class="dt">se=</span><span class="ot">FALSE</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-101-1.png" width="672" /></p>
</div>
<div id="acc060-model-interpretations" class="section level3">
<h3><span class="header-section-number">2.8.8</span> Acc060 Model Interpretations</h3>
<p><span class="math inline">\(\widehat{Price} = b_0 + b_1\times\text{Acc. Time}\)</span></p>
<p><span class="math inline">\(\widehat{Price} = 89.90 - 7.193\times\text{Acc. Time}\)</span></p>
<ul>
<li><p>Intercept <span class="math inline">\(b_0\)</span> might be interpreted as the price of a car that can accelerate from 0 to 60 in no time, but this is not a meaningful interpretation since there are no such cars.</p></li>
<li><p><span class="math inline">\(b_1=-7.1933\)</span> tells us that on average, the price of a car is expected to decrease by 7.19 thousand dollars for each additional second it takes to accelerate from 0 to 60 mph.</p></li>
<li><p><span class="math inline">\(R^2 = 0.5521\)</span> tells us that 55% of the variation in price is explained by the linear model using acceleration time as the explanatory variable.</p></li>
</ul>
</div>
<div id="modeling-price-using-acc060-and-length" class="section level3">
<h3><span class="header-section-number">2.8.9</span> Modeling Price using Acc060 and Length</h3>
<p><span class="math inline">\(\widehat{Price} = b_0 + b_1\times\text{Acc. Time} + b_2\times\text{Length}\)</span></p>
<p><strong>Model Assumptions:</strong></p>
<ul>
<li><p>Assumes expected price is a linear function of acceleration time and length.</p></li>
<li><p>Assumes that expected price increases at same rate with respect to acc. time, for cars of all lengths.</p></li>
<li><p>Assumes that expected price increases at same rate with respect to length, for cars of all acceleration times.</p></li>
</ul>
</div>
<div id="model-using-length-and-acceleration-time" class="section level3">
<h3><span class="header-section-number">2.8.10</span> Model Using Length and Acceleration Time</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Cars_M_A060_L &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Cars2015, LowPrice <span class="op">~</span><span class="st"> </span>Acc060 <span class="op">+</span><span class="st"> </span>Length)
<span class="kw">summary</span>(Cars_M_A060_L)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = LowPrice ~ Acc060 + Length, data = Cars2015)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -27.969  -6.625  -1.418   4.934  28.394 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept) 51.83936   18.00737   2.879             0.00482 ** 
## Acc060      -6.48340    0.69248  -9.363 0.00000000000000141 ***
## Length       0.17316    0.07874   2.199             0.03003 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.52 on 107 degrees of freedom
## Multiple R-squared:  0.5715, Adjusted R-squared:  0.5635 
## F-statistic: 71.36 on 2 and 107 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
<div id="regression-plane" class="section level3">
<h3><span class="header-section-number">2.8.11</span> Regression Plane</h3>
<p><span class="math inline">\(\widehat{Price} = b_0 + b_1\times\text{Acc. Time} + b_2\times\text{Length}\)</span></p>
<p><span class="math inline">\(\widehat{Price} = 51.83936 + -6.48340\times\text{Acc. Time} + 0.17316\times\text{Length}\)</span></p>
<p><img src="Plane.png" width="40%" /></p>
<p>We can further explore the regression plane <a href="https://academo.org/demos/3d-surface-plotter/?expression=51.89-6.48*x%2B0.17*y&amp;xRange=0%2C%2B14&amp;yRange=150%2C+200&amp;resolution=21">academo.org</a>.</p>
</div>
<div id="acc060-and-length-model-interpretations" class="section level3">
<h3><span class="header-section-number">2.8.12</span> Acc060 and Length Model Interpretations</h3>
<p><span class="math inline">\(\widehat{Price} = b_0 + b_1\times\text{Acc. Time} + b_2\times\text{Length}\)</span></p>
<p><span class="math inline">\(\widehat{Price} = 51.83936 + -6.48340\times\text{Acc. Time} + 0.17316\times\text{Length}\)</span></p>
<ul>
<li><p>Intercept <span class="math inline">\(b_0\)</span> might be interpreted as the price of a car that can accelerate from 0 to 60 in no time and has length 0, but this is not a meaningful interpretation since there are no such cars.</p></li>
<li><p><span class="math inline">\(b_1=-6.4834\)</span> tells us that on average, the price of a car is expected to decrease by 6.48 thousand dollars for each additional second it takes to accelerate from 0 to 60 mph., assuming length is held constant.</p></li>
<li><p><span class="math inline">\(b_2=0.17316\)</span> tells us that on average, the price of a car is expected to increase by 0.173 thousand dollars (or <span class="math inline">\(173\)</span>) for each additional inch in length, assuming the time it takes to accelerate from 0 to 60 mph. is held constant.</p></li>
<li><p><span class="math inline">\(R^2 = 0.5715\)</span> tells us that 57% of the variation in price is explained by the linear model using acceleration time and length as the explanatory variables.</p></li>
</ul>
</div>
<div id="modeling-price-using-acc060-and-length-with-interaction" class="section level3">
<h3><span class="header-section-number">2.8.13</span> Modeling Price using Acc060 and Length with Interaction</h3>
<p><span class="math inline">\(\widehat{Price} = b_0 + b_1\times\text{Acc. Time} + b_2\times\text{Length}+ b_3\times\text{Acc. Time}\times\text{Length}\)</span></p>
<p><strong>Model Assumptions:</strong></p>
<ul>
<li><p>Assumes expected price is a linear function of acceleration time and length.</p></li>
<li><p>Assumes that rate of increase in expected price increases with respect to acc. time differs depending on length of the car.</p></li>
<li><p>Assumes that rate of increase in expected price increases with respect to length differs depending on acceleration time of the car.</p></li>
</ul>
</div>
<div id="predictions-using-price-acc060-length-model-with-interaction" class="section level3">
<h3><span class="header-section-number">2.8.14</span> Predictions using Price, Acc060, Length Model with Interaction</h3>
<p><span class="math inline">\(\widehat{Price} = b_0 + b_1\times\text{Acc. Time} + b_2\times\text{Length} + b_3\times\text{Acc. Time}\times\text{Length}\)</span></p>
<p>Predicted Price for 150 inch car:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{Price} &amp; = b_0 + b_1\times\text{Acc. Time} + b_2\times150 + b_3\times\text{Acc. Time}\times150 \\
 &amp;= (b_0 + 150b_2) + (b_1+150b_3)\times\text{Acc. Time}
\end{aligned}
\]</span></p>
<p>Predicted Price for 200 inch car:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{Price} &amp; = b_0 + b_1\times\text{Acc. Time} + b_2\times 200 + b_3\times\text{Acc. Time}\times 200 \\
 &amp;= (b_0 + 200b_2) + (b_1+200b_3)\times\text{Acc. Time}
\end{aligned}
\]</span></p>
</div>
<div id="interaction-model-for-quantitative-variables" class="section level3">
<h3><span class="header-section-number">2.8.15</span> Interaction Model for Quantitative Variables</h3>
<p>We specify an interaction model in R using the <code>*</code> between the explanatory variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Cars_M_A060_L_Int &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data=</span>Cars2015, LowPrice <span class="op">~</span><span class="st"> </span>Acc060 <span class="op">*</span><span class="st"> </span>Length)
<span class="kw">summary</span>(Cars_M_A060_L_Int)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = LowPrice ~ Acc060 * Length, data = Cars2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -31.0782  -5.2974  -0.6007   4.2479  31.3622 
## 
## Coefficients:
##                 Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)   -160.25438   54.11260  -2.961   0.00378 ** 
## Acc060          19.00490    6.21545   3.058   0.00282 ** 
## Length           1.34893    0.29447   4.581 0.0000127 ***
## Acc060:Length   -0.14260    0.03459  -4.123 0.0000745 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.814 on 106 degrees of freedom
## Multiple R-squared:  0.6307, Adjusted R-squared:  0.6203 
## F-statistic: 60.35 on 3 and 106 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
<div id="cars-interaction-model-interpretations" class="section level3">
<h3><span class="header-section-number">2.8.16</span> Cars Interaction Model Interpretations</h3>
<p><span class="math inline">\(\widehat{Price} = -160.25438 + 19.00490\times\text{Acc. Time} + 1.34893\times\text{Length} - 0.14260\times\text{Acc. Time}\times\text{Length}\)</span></p>
<p>For a car that is 150 inches long:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{Price} &amp; = -160.25438 + 19.00490\times\text{Acc. Time} + 1.34893\times150 - 0.14260\times\text{Acc. Time}\times150 \\
 &amp;= 42.085 -2.385\times\text{Acc. Time} 
\end{aligned}
\]</span></p>
<p>For a 150 inch car, price is expected to decrease by 2.385 thousand dollars for each additional second it takes to accelerate from 0 to 60 mph.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{Price} &amp; = -160.25438 + 19.00490\times\text{Acc. Time} + 1.34893\times200 - 0.14260\times\text{Acc. Time}\times200 \\
 &amp;= 109.532 -9.515\times\text{Acc. Time} 
\end{aligned}
\]</span></p>
<p>For a 200 inch car, price is expected to decrease by 9.515 thousand dollars for each additional second it takes to accelerate from 0 to 60 mph.</p>
<p>When using an interaction model, we can only interpret coefficients with respect to one variable for a given value of the other variable.</p>
<p><span class="math inline">\(R^2=0.6307\)</span> tells us that 63% of variation in car price is explained by the model using length and acceleration time with interaction.</p>
</div>
<div id="predicting-car-price-using-predict" class="section level3">
<h3><span class="header-section-number">2.8.17</span> Predicting Car Price Using <code>predict</code></h3>
<p>Predict the price of a 200 inch car that can acclerate from 0 to 60 mph in 8 seconds.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(Cars_M_A060_L_Int, <span class="dt">newdata=</span><span class="kw">data.frame</span>(<span class="dt">Acc060=</span><span class="dv">8</span>, <span class="dt">Length=</span><span class="dv">200</span>))</code></pre></div>
<pre><code>##        1 
## 33.40344</code></pre>
<p>Predict the price of a 150 inch car that can acclerate from 0 to 60 mph in 10 seconds.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(Cars_M_A060_L_Int, <span class="dt">newdata=</span><span class="kw">data.frame</span>(<span class="dt">Acc060=</span><span class="dv">10</span>, <span class="dt">Length=</span><span class="dv">150</span>))</code></pre></div>
<pre><code>##        1 
## 18.22735</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cross.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-intro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
